/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package production;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static production.dbCon.con;

/**
 *
 * @author Axio
 */
public class editProcessPlan extends javax.swing.JFrame {
    
    int ppno;
    String type="";
    String blp="";
    String style="";
    String cus="";
    String col="";
    String date="";
    String emp="";
    String wsu="";
    String bcqc="";
    String bwst="";
    /**
     * Creates new form editProcessPlan
     */
    public editProcessPlan() throws SQLException {
        initComponents();
    }
    
    public editProcessPlan(int p, String b, String s, String cu, String c, String d, String t, String w, String e, String bc, String bw) throws SQLException {
        initComponents();
        type = t;
        blp = b;
        style = s;
        cus = cu;
        col = c;
        date = d;
        emp = e;
        wsu = w;
        bcqc = bc;
        bwst = bw;
        ppno = p;
        
        dbCon da = new dbCon();
        da.connect();
        
        ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT type FROM processplan");
        while(rs.next()){
            PPType.addItem(rs.getString("type"));
        }
        ResultSet rs1 = con.createStatement().executeQuery("SELECT BLP_No FROM processplan WHERE type ='"+type+"'");
        while(rs1.next()){
            PPBLPno.addItem(rs1.getString("BLP_No"));
        }
        /*ResultSet rs2 = con.createStatement().executeQuery("SELECT eid FROM employee");
        while(rs2.next()){
            PPEmp.addItem(rs2.getString("BLP_No"));
        }
        ResultSet rs3 = con.createStatement().executeQuery("SELECT eid FROM employee");
        while(rs3.next()){
            PPWSu.addItem(rs3.getString("BLP_No"));
        }
        ResultSet rs4 = con.createStatement().executeQuery("SELECT eid FROM employee");
        while(rs4.next()){
            PPBWSt.addItem(rs4.getString("BLP_No"));
        }
        ResultSet rs5 = con.createStatement().executeQuery("SELECT eid FROM employee");
        while(rs5.next()){
            PPBC.addItem(rs5.getString("BLP_No"));
        }*/
        
        PPno.setText(Integer.toString(ppno));
        PPType.setSelectedItem(type);
        PPBLPno.setSelectedItem(blp);
        PPCus.setText(cus);
        PPStyleno.setText(style);
        PPCol.setText(col);
        PPDate.setText(date);
        PPEmp.setSelectedItem(emp);
        PPWSu.setSelectedItem(wsu);
        PPBWSt.setSelectedItem(bwst);
        PPBC.setSelectedItem(bcqc);
        
        PPType.setEnabled(false);
        PPBLPno.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        PPCus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PPType = new javax.swing.JComboBox<>();
        PPBLPno = new javax.swing.JComboBox<>();
        PPno = new javax.swing.JLabel();
        PPEmp = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PPStyleno = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PPCol = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PPBWSt = new javax.swing.JComboBox<>();
        PPWSu = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        PPBC = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        PPDate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 470));
        setMinimumSize(new java.awt.Dimension(720, 470));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(720, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 710, 13));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Edit Process Plan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 372, -1));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 710, 13));

        jLabel2.setText("Customer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 60, 30));

        PPCus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PPCus.setText("<<Customer>>");
        jPanel1.add(PPCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 160, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save Edited");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 130, 40));

        jPanel1.add(PPType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 120, 35));

        jPanel1.add(PPBLPno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 190, 35));

        PPno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PPno.setText("<<Process Plan No>>");
        jPanel1.add(PPno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 170, 30));

        jPanel1.add(PPEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 160, 35));

        jLabel5.setText("Employee");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 70, 35));

        jLabel6.setText("Style No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 50, 30));

        PPStyleno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PPStyleno.setText("<<Style_No>>");
        jPanel1.add(PPStyleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 160, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Close.png"))); // NOI18N
        close.setAlignmentY(0.0F);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Minimize.png"))); // NOI18N
        minimize.setAlignmentY(0.0F);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        jLabel9.setText("Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, 35));

        jLabel10.setText("Color");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 50, 30));

        PPCol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PPCol.setText("<<Color>>");
        jPanel1.add(PPCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 160, 30));

        jLabel12.setText("B/W Store");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 70, 35));

        jPanel1.add(PPBWSt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 160, 35));

        jPanel1.add(PPWSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 160, 35));

        jLabel13.setText("W Supervisor");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 80, 35));

        jPanel1.add(PPBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 160, 35));

        jLabel14.setText("Date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 50, 35));

        PPDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PPDate.setText("YYYY-MM-DD");
        jPanel1.add(PPDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 160, 40));

        jLabel15.setText("BC QC");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 50, 35));

        jLabel8.setText("Batch/Portion/Lot No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Process Plan No :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String p = String.valueOf(PPno.getText());
        String type1 = String.valueOf(PPType.getSelectedItem());
        String blp1 = String.valueOf(PPBLPno.getSelectedItem());
        String emp1 = String.valueOf(PPEmp.getSelectedItem());
        String bwst1 = String.valueOf(PPBWSt.getSelectedItem());
        String wsu1 = String.valueOf(PPWSu.getSelectedItem());
        String bcqc1 = String.valueOf(PPBC.getSelectedItem());
        
        int pno = Integer.parseInt(p);
        
        try {
            con.prepareStatement("UPDATE processplan set W_Supervisor = '"+wsu1+"', Employee = '"+emp1+"', BC_QC = '"+bcqc1+"', BW_Store = '"+bwst1+"' WHERE Process_No = "+pno+"").execute();
            JOptionPane.showMessageDialog (null, "Process Plan Updated", "Done", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(editProcessPlan.class.getName()).log(Level.SEVERE, null, ex);
        }

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editProcessPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editProcessPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editProcessPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editProcessPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new editProcessPlan().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(editProcessPlan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PPBC;
    private javax.swing.JComboBox<String> PPBLPno;
    private javax.swing.JComboBox<String> PPBWSt;
    private javax.swing.JLabel PPCol;
    private javax.swing.JLabel PPCus;
    private javax.swing.JTextField PPDate;
    private javax.swing.JComboBox<String> PPEmp;
    private javax.swing.JLabel PPStyleno;
    private javax.swing.JComboBox<String> PPType;
    private javax.swing.JComboBox<String> PPWSu;
    private javax.swing.JLabel PPno;
    private javax.swing.JLabel close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
