/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package production;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static production.dbCon.con;

/**
 *
 * @author Axio
 */
public class editlistAQLandFB extends javax.swing.JFrame {
    
    String b="";
    String s="";
    String c="";
    String cu="";
    String t="";
    int firstbath;
    int aq;
    /**
     * Creates new form editFB
     * @throws java.sql.SQLException
     */
    public editlistAQLandFB() throws SQLException {
        initComponents();
        
        dbCon d = new dbCon();
        d.connect();
    }
    
    public editlistAQLandFB(String blp, String style, String col, String cus, String type, int fb, int aql) throws SQLException {
        initComponents();
        b = blp;
        s = style;
        c = col;
        cu = cus;
        t  = type;
        firstbath = fb;
        aq = aql;
        
        dbCon d = new dbCon();
        d.connect();
        
        ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT type FROM listaqlandfb");
        while(rs.next()){
            FBIType.addItem(rs.getString("type"));
        }
        ResultSet rs2 = con.createStatement().executeQuery("SELECT BLP_No FROM listaqlandfb WHERE type ='"+t+"'");
        while(rs2.next()){
            FBIBLPno.addItem(rs2.getString("BLP_No"));
        }
        
        FBIType.setSelectedItem(t);
        FBIBLPno.setSelectedItem(b);
        FBICusno.setText(cu);
        FBIStyleno.setText(s);
        FBIColor.setText(c);
        
        if(firstbath == 0)
        {
            FBIFB.setSelectedItem("Fail");
        }
        else
        {
            FBIFB.setSelectedItem("Pass");
        }
        
        if(aq == 0)
        {
            FBIAQL.setSelectedItem("Fail");
        }
        else
        {
            FBIAQL.setSelectedItem("Pass");
        }
        
        FBIType.setEnabled(false);
        FBIBLPno.setEnabled(false);
        FBIFB.setEnabled(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        FBICusno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FBIType = new javax.swing.JComboBox<>();
        FBIBLPno = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        FBIFB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FBIStyleno = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FBIColor = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FBIAQL = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 470));
        setMinimumSize(new java.awt.Dimension(720, 470));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(720, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 710, 13));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Edit List AQL and First Bath");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 372, -1));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 710, 13));

        jLabel2.setText("Customer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 60, 30));

        FBICusno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FBICusno.setText("<<Customer>>");
        jPanel1.add(FBICusno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save Edited");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 130, 40));

        jPanel1.add(FBIType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 35));

        jPanel1.add(FBIBLPno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, 35));

        jLabel7.setText("Batch/Portion/Lot No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        FBIFB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pass", "Fail" }));
        FBIFB.setSelectedIndex(-1);
        jPanel1.add(FBIFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 160, 35));

        jLabel5.setText("First Bath Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 90, 35));

        jLabel6.setText("Style No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 50, 30));

        FBIStyleno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FBIStyleno.setText("<<Style_No>>");
        jPanel1.add(FBIStyleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Close.png"))); // NOI18N
        close.setAlignmentY(0.0F);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Minimize.png"))); // NOI18N
        minimize.setAlignmentY(0.0F);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        jLabel9.setText("Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 40, 35));

        jLabel10.setText("Color");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 50, 30));

        FBIColor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FBIColor.setText("<<Color>>");
        jPanel1.add(FBIColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 160, 30));

        jLabel12.setText("AQL");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 40, 35));

        FBIAQL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pass", "Fail" }));
        FBIAQL.setSelectedIndex(-1);
        jPanel1.add(FBIAQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 160, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fb = String.valueOf(FBIFB.getSelectedItem());
        String type = String.valueOf(FBIType.getSelectedItem());
        String blp = String.valueOf(FBIBLPno.getSelectedItem());
        String aql = String.valueOf(FBIAQL.getSelectedItem());
        
        if(fb.equals("Pass")){
            if(aql.equals("Pass"))
            {
                try {
                    con.prepareStatement("UPDATE listaqlandfb set AQL=1 WHERE BLP_No ='"+blp+"'").execute();
                    
                    if(type.equals("Gloves")){ //If type is set to Gloves the below line updates the SQLGlove table's aql value                    
                        con.prepareStatement("UPDATE SPLGlove set AQL_FB_Status = 1 WHERE lotNo = '"+blp+"'").execute();                    
                    } else if(type.equals("Garment")){ //If type is set to Garments the below line updates the SQLGarment table's aql value                    
                        con.prepareStatement("UPDATE SPLGarment set AQL_FB_Status = 1 WHERE portionNo = '"+blp+"'").execute();                    
                    } else { //If type is set to Fabrics the below line updates the SQLFabric table's aql value                     
                        con.prepareStatement("UPDATE SPLFabric set AQL_FB_Status = 1 WHERE batchNo = '"+blp+"'").execute();
                    }
                    
                    JOptionPane.showMessageDialog (null, "AQL Value Updated", "Done", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                } catch (SQLException ex) {
                    Logger.getLogger(editlistAQLandFB.class.getName()).log(Level.SEVERE, null, ex);
                } 
            } else {
                try {
                    con.prepareStatement("UPDATE listaqlandfb set AQL=0 WHERE BLP_No ='"+blp+"'").execute();
                    
                    if(type.equals("Gloves")){ //If type is set to Gloves the below line updates the SQLGlove table's aql value                    
                        con.prepareStatement("UPDATE SPLGlove set AQL_FB_Status = 0 WHERE lotNo = '"+blp+"'").execute();                    
                    } else if(type.equals("Garment")){ //If type is set to Garments the below line updates the SQLGarment table's aql value                    
                        con.prepareStatement("UPDATE SPLGarment set AQL_FB_Status = 0 WHERE portionNo = '"+blp+"'").execute();                    
                    } else { //If type is set to Fabrics the below line updates the SQLFabric table's aql value                     
                        con.prepareStatement("UPDATE SPLFabric set AQL_FB_Status = 0 WHERE batchNo = '"+blp+"'").execute();
                    }
                    
                    JOptionPane.showMessageDialog (null, "AQL Value Updated", "Done", JOptionPane.INFORMATION_MESSAGE);
                    
                    this.setVisible(false);
                } catch (SQLException ex) {
                    Logger.getLogger(editlistAQLandFB.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        } else {
            if(aql.equals("Pass")){
                JOptionPane.showMessageDialog (null, "AQL CANNOT be PASSED because First Bath is FAILED", "Error", JOptionPane.ERROR_MESSAGE);
                this.setVisible(false);
            } else {
                try {
                    con.prepareStatement("UPDATE listaqlandfb set AQL=0 WHERE BLP_No ='"+blp+"'").execute();
                    
                    /*if(type.equals("Gloves")){ //If type is set to Gloves the below line updates the SQLGlove table's aql value                    
                        con.prepareStatement("UPDATE SPLGlove set AQL_FB_Status = 0 WHERE lotNo = '"+blp+"'").execute();                    
                    } else if(type.equals("Garment")){ //If type is set to Garments the below line updates the SQLGarment table's aql value                    
                        con.prepareStatement("UPDATE SPLGarment set AQL_FB_Status = 0 WHERE portionNo = '"+blp+"'").execute();                    
                    } else { //If type is set to Fabrics the below line updates the SQLFabric table's aql value                     
                        con.prepareStatement("UPDATE SPLFabric set AQL_FB_Status = 0 WHERE batchNo = '"+blp+"'").execute();
                    }*/
                    
                    JOptionPane.showMessageDialog (null, "AQL Value Updated", "Done", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                } catch (SQLException ex) {
                    Logger.getLogger(editlistAQLandFB.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editlistAQLandFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editlistAQLandFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editlistAQLandFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editlistAQLandFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new editlistAQLandFB().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(editlistAQLandFB.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FBIAQL;
    private javax.swing.JComboBox<String> FBIBLPno;
    private javax.swing.JLabel FBIColor;
    private javax.swing.JLabel FBICusno;
    private javax.swing.JComboBox<String> FBIFB;
    private javax.swing.JLabel FBIStyleno;
    private javax.swing.JComboBox<String> FBIType;
    private javax.swing.JLabel close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
