package ITP;


import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Tenusha
 */
public class addCustomer extends javax.swing.JFrame {
    /**
     * Creates new form addNewStyleData
     */
    int emailcheck=0;
    int phonecheck=0;
    methods m = new methods();
    int edit=0;
    String primary_key=null;
    listCustomers c = new listCustomers();
    
    public addCustomer(){
        initComponents();
        m.dbConnection();
        jPanel2.setVisible(false);
    }

    public addCustomer(String primaryKey){
        initComponents();
        edit=1;
        primary_key=primaryKey;
        try {
            m.dbConnection();
            ResultSet rs = m.st.executeQuery("select * from customer where custID ='"+primaryKey+"'");
            if(!rs.next()==false){
                jLabel26.setText(rs.getString(1));
                name.setText(rs.getString(2));
                email.setText(rs.getString(3));
                phone.setText(rs.getString(4));
                address.setText(rs.getString(5));
                city.setText(rs.getString(6));
                bAddress.setText(rs.getString(7));
                bAddress1.setText(rs.getString(8));
                bAddress2.setText(rs.getString(9));
                bAddress3.setText(rs.getString(10));
                state.setText(rs.getString(11));
                pCode.setText(rs.getString(12));
                vatNo.setText(rs.getString(13));
                svatNo.setText(rs.getString(14));
                jPanel2.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText("Edit Customer");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addCustomer = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bAddress1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bAddress2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bAddress3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pCode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        vatNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        svatNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Style");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(514, 482));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCustomer.setBackground(new java.awt.Color(10, 24, 224));
        addCustomer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addCustomer.setForeground(new java.awt.Color(255, 255, 255));
        addCustomer.setText("+ Add");
        addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(addCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 100, 30));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 100, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("*");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("*");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 210, -1));

        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 210, -1));

        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 210, -1));

        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 210, -1));

        city.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFocusGained(evt);
            }
        });
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("City");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Phone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Company");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Billing Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 90, -1));

        bAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bAddressFocusGained(evt);
            }
        });
        jPanel1.add(bAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Billing Address1");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        bAddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bAddress1FocusGained(evt);
            }
        });
        jPanel1.add(bAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 210, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Billing Address2");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        bAddress2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bAddress2FocusGained(evt);
            }
        });
        jPanel1.add(bAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 210, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Billing Address3");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        bAddress3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bAddress3FocusGained(evt);
            }
        });
        jPanel1.add(bAddress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 210, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("State");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 90, -1));

        state.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateFocusGained(evt);
            }
        });
        jPanel1.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 210, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Postal Code");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, -1));

        pCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pCodeFocusGained(evt);
            }
        });
        jPanel1.add(pCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 210, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("VAT No");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 90, -1));

        vatNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vatNoFocusGained(evt);
            }
        });
        jPanel1.add(vatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 210, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("SVAT No");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 90, -1));

        svatNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                svatNoFocusGained(evt);
            }
        });
        jPanel1.add(svatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 210, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("New Customer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 910, 20));

        jLabel2.setText("Please enter the information below. fields with * are required.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("*");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Minimize.png"))); // NOI18N
        jLabel22.setText("jLabel14");
        jLabel22.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel22.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel22.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Close.png"))); // NOI18N
        jLabel21.setText("jLabel14");
        jLabel21.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel21.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel21.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Customer ID");
        jLabel25.setAlignmentY(0.0F);

        jLabel26.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 350, 100));

        error.setForeground(java.awt.Color.red);
        error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 560, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        String c_name=name.getText();
	String c_email=email.getText();
	String c_phone=phone.getText();
        //String c_company=company.getText();
	String c_address=address.getText();
	String c_city=city.getText();
	String c_ba=bAddress.getText();
	String c_ba1=bAddress1.getText();
	String c_ba2=bAddress2.getText();
	String c_ba3=bAddress3.getText();
	String c_state=state.getText();
	String c_pc=pCode.getText();
	String c_vat=vatNo.getText();
	String c_svat=svatNo.getText();
        boolean vat=true;
        
        vat=m.validateVAT(c_vat);
        
        if(!c_name.equals("")){
            if(m.validateEmail(c_email)){
                if(!c_phone.equals("")){
                    if(m.validatePhone(c_phone, error)){
                        //if(!c_company.equals("")){
                            if(!c_address.equals("")){
                                if(vat){
                                    try {
                                        if(m.validateUniqueFeild(vatNo, error, "customer", "vat", edit)){
                                            try {
                                                
                                                if(m.checkSubmit()){
                                                    
                                                    if(edit==1){
                                                        m.st.executeUpdate("UPDATE customer SET name='"+c_name+"', email='"+c_email+"', phone='"+c_phone+"', address='"+c_address+"', city='"+c_city+"', ba='"+c_ba+"', ba1='"+c_ba1+"', ba2='"+c_ba2+"', ba3='"+c_ba3+"', state='"+c_state+"', pc='"+c_pc+"', vat='"+c_vat+"', svat='"+c_svat+"' WHERE custID='"+primary_key+"'");
                                                        m.dynamicTable(c.jTextField1, c.jComboBox1, c.pageNo, c.jTable1, "customer", "custID, name, email, phone, address, city, ba, state, pc, vat, svat");
                                                    }
                                                    else{
                                                        m.st.executeUpdate("INSERT INTO customer (name, email, phone, address, city, ba, ba1, ba2, ba3, state, pc, vat, svat)" +
                                                                " VALUES ('"+c_name+"', '"+c_email+"', '"+c_phone+"', '"+c_address+"', '"+c_city+"', '"+c_ba+"', '"+c_ba1+"', '"+c_ba2+"', '"+c_ba3+"', '"+c_state+"', '"+c_pc+"', " +
                                                                        "'"+c_vat+"', '"+c_svat+"')");
                                                        m.dynamicTable(c.jTextField1, c.jComboBox1, c.pageNo, c.jTable1, "customer", "custID, name, email, phone, address, city, ba, state, pc, vat, svat");
                                                    }
                                                    
                                                    ResultSet rs2= m.st.executeQuery("select MAX(custID) from customer");
                                                    rs2.next();
                                                    if(edit!=1){
                                                        JOptionPane.showMessageDialog(null, "successfully added !\ncustomer id ="+rs2.getString(1));
                                                        this.dispose();
                                                        new addCustomer().setVisible(true);
                                                    }else{
                                                        JOptionPane.showMessageDialog(null, "successfully updated.");
                                                        this.dispose();
                                                    }
                                                }
                                                
                                                
                                            } catch (SQLException ex) {
                                                Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                        }else{
                                            vatNo.setBorder(BorderFactory.createLineBorder (Color.red));
                                            if(c_vat.equals("")){
                                                error.setText("VAT No field cannot be empty !");
                                            }
                                        }
                                    } catch (SQLException ex) {
                                        Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                }else {vatNo.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Invalid VAT Number !");}
                            }else {address.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Address field cannot be empty !");}
                        //}else{company.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Company field cannot be empty !");}
                    }else {phone.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Invalid Phone number !");}
                }else {phone.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Phone field cannot be empty !");}
            }else{email.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Invalid email address !");}
        }else {name.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Company field cannot be empty !");}
        
    }//GEN-LAST:event_addCustomerActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_CancelActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        name.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        name.setForeground(Color.black);
    }//GEN-LAST:event_nameFocusGained

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        email.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        email.setForeground(Color.black);
    }//GEN-LAST:event_emailFocusGained

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
        phone.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        phone.setForeground(Color.black);
    }//GEN-LAST:event_phoneFocusGained

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        address.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        address.setForeground(Color.black);
    }//GEN-LAST:event_addressFocusGained

    private void cityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFocusGained
        // TODO add your handling code here:
        city.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        city.setForeground(Color.black);
    }//GEN-LAST:event_cityFocusGained

    private void bAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bAddressFocusGained
        // TODO add your handling code here:
        bAddress.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        bAddress.setForeground(Color.black);
    }//GEN-LAST:event_bAddressFocusGained

    private void bAddress1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bAddress1FocusGained
        // TODO add your handling code here:
        bAddress1.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        bAddress1.setForeground(Color.black);
    }//GEN-LAST:event_bAddress1FocusGained

    private void bAddress2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bAddress2FocusGained
        // TODO add your handling code here:
        bAddress2.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        bAddress2.setForeground(Color.black);
    }//GEN-LAST:event_bAddress2FocusGained

    private void bAddress3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bAddress3FocusGained
        // TODO add your handling code here:
        bAddress3.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        bAddress3.setForeground(Color.black);
    }//GEN-LAST:event_bAddress3FocusGained

    private void stateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFocusGained
        // TODO add your handling code here:
        state.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        state.setForeground(Color.black);
    }//GEN-LAST:event_stateFocusGained

    private void pCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCodeFocusGained
        // TODO add your handling code here:
        pCode.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        pCode.setForeground(Color.black);
    }//GEN-LAST:event_pCodeFocusGained

    private void vatNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vatNoFocusGained
        // TODO add your handling code here:
        vatNo.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        vatNo.setForeground(Color.black);
    }//GEN-LAST:event_vatNoFocusGained

    private void svatNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_svatNoFocusGained
        // TODO add your handling code here:
        svatNo.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        svatNo.setForeground(Color.black);
    }//GEN-LAST:event_svatNoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton addCustomer;
    private javax.swing.JTextField address;
    private javax.swing.JTextField bAddress;
    private javax.swing.JTextField bAddress1;
    private javax.swing.JTextField bAddress2;
    private javax.swing.JTextField bAddress3;
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pCode;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField state;
    private javax.swing.JTextField svatNo;
    private javax.swing.JTextField vatNo;
    // End of variables declaration//GEN-END:variables
}
