package ITP;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tenusha
 */
public final class addEmployee extends javax.swing.JFrame {
    /**
     * Creates new form addNewStyleData
     */
    methods m = new methods();
    int edit=0;
    String primary_key=null;
    int emailcheck=0;
    int phonecheck=0;
    String fileName=null;
    int s=0;
    byte[] person_image=null;
    
    DateFormat df=new SimpleDateFormat("dd-MM-yyyy");
    Date date1= new Date();
    
    ButtonGroup group = new ButtonGroup();
    listEmployees l = new listEmployees();
    public addEmployee(){
        initComponents();
        setcombobox();
        date.setDate(date1);
        group.add(male);
        group.add(female);
    
        m.dbConnection();
    }

    public addEmployee(String primaryKey) throws ParseException{
        edit=1;
        initComponents();
        setcombobox();
        date.setDate(date1);
        group.add(male);
        group.add(female);
        primary_key=primaryKey;
        try {
            m.dbConnection();
            ResultSet rs = m.st.executeQuery("select * from employee where empNo ='"+primaryKey+"'");
            rs.next();
            epfNo.setText(rs.getString("epfNo"));
            name.setText(rs.getString(3));
            
            name1.setText(rs.getString(4));
            email.setText(rs.getString(6));
            phone.setText(rs.getString(7));
            address.setText(rs.getString(8));
            dob.setText(rs.getString(9));
            nic.setText(rs.getString(10));
            
            String u_level=rs.getString("user_level");
            switch(u_level){
                case "0": jComboBox1.setSelectedIndex(0); break;
                case "1": jComboBox1.setSelectedIndex(1); break;
                case "2": jComboBox1.setSelectedIndex(2); break;
                case "3": jComboBox1.setSelectedIndex(3); break;
                case "4": jComboBox1.setSelectedIndex(4); break;
                case "5": jComboBox1.setSelectedIndex(5); break;   
            }
            
            String gender = rs.getString("gender");
            if(gender.equals("Male")){
                male.setSelected(true);
            }
            else if(gender.equals("Female")){
                female.setSelected(true);
            }
            //m.loadImage(primaryKey, img);
            //date.setText(rs.getString(11));
            String s=rs.getString(11);
            DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            Date ed=df.parse(s);
            date.setDate(ed);
        } catch (SQLException ex) {
            Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        //epfNo.setText(primaryKey);
        m.getImage(img, primaryKey);
        epfNo.setEditable(false);
        jLabel1.setText("Edit Employee");
    }
    String getGender(){
        if(male.isSelected()){
            return "Male";
        }
        else if(female.isSelected()){
            return "Female";
        }
        else return null;
    }
    void setcombobox(){
        if(Home.user_level!=5){
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Data Entry Operator");
            jComboBox1.addItem("Driver");
            jComboBox1.addItem("Machine Repair");
            jComboBox1.addItem("Supervisor");
            jComboBox1.addItem("Manager");
            jComboBox1.setSelectedIndex(-1);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addCustomer = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        epfNo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        imgPath = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        error = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        date = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Style");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(514, 482));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCustomer.setBackground(new java.awt.Color(10, 24, 224));
        addCustomer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addCustomer.setForeground(new java.awt.Color(255, 255, 255));
        addCustomer.setText("+  Add");
        addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(addCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 100, 30));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 100, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("*");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("*");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("*");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, -1));

        dob.setText("dd-mm-yyyy");
        dob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dobFocusGained(evt);
            }
        });
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 210, -1));

        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 210, -1));

        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 210, -1));

        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Date Of Birth");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Phone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("NIC No");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 90, -1));

        nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nicFocusGained(evt);
            }
        });
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 210, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("User Level");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, 20));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("New Employee");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 530, 20));

        jLabel2.setText("Please enter the information below. fields with * are required.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("EPF No");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

        epfNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                epfNoFocusGained(evt);
            }
        });
        epfNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epfNoActionPerformed(evt);
            }
        });
        jPanel1.add(epfNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 210, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("*");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("*");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Joined date");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 100, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Data Entry Operator", "Driver", "Machine Repair", "Supervisor", "Manager", "Admin" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, -1));

        name1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name1FocusGained(evt);
            }
        });
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("*");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 10, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("*");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 20, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("*");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jButton1.setText("Attach Image..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 110, -1));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/profile1.jpg"))); // NOI18N
        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        img.setMaximumSize(new java.awt.Dimension(120, 180));
        img.setMinimumSize(new java.awt.Dimension(120, 180));
        img.setPreferredSize(new java.awt.Dimension(103, 132));
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));
        jPanel1.add(imgPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 150, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, -1));

        male.setText("Male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        female.setText("Female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        error.setForeground(java.awt.Color.red);
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 210, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Minimize.png"))); // NOI18N
        jLabel16.setText("jLabel14");
        jLabel16.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel16.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel16.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Close.png"))); // NOI18N
        jLabel26.setText("jLabel14");
        jLabel26.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel26.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel26.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 30));

        date.setFormats("dd-MM-yyyy");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        String e_epfno=epfNo.getText();
        String e_fname=name.getText();
        String e_lname=name1.getText();
        String e_gender=getGender();
	String e_email=email.getText();
	String e_phone=phone.getText();
	String e_address=address.getText();
	String e_dob=dob.getText();
	String e_nic=nic.getText();
        Date d=date.getDate();
        Format df1=new SimpleDateFormat("dd-MM-yyyy");
        String e_jdate=df1.format(d);
	//String e_jdate=date.getText();
        
	int e_ul=jComboBox1.getSelectedIndex();
        int pwd=e_nic.hashCode();
        boolean epf=true;
        epf=m.validateEPF(e_epfno);
        if(epf){
            try {
                if(!e_epfno.equals("")){
                    if(m.validateUniqueFeild(epfNo, error, "employee", "epfNo", edit)){
                        if(!e_fname.equals("")){
                            if(!e_lname.equals("")){
                                if(m.validateEmail(e_email) && m.validateUniqueFeild(email, error, "employee","email", edit)){ 
                                    //if(!e_phone.equals("")){
                                    if(m.validatePhone(e_phone, error)){    
                                        if(!e_address.equals("")){
                                            if(m.validateBirthday(e_dob, error)){
                                                if(!e_nic.equals("")&& m.validateNIC(e_nic) && m.validateUniqueFeild(nic, error, "employee","nic", edit)){
                                                    
                                                        try {
                                                            if(m.checkSubmit()){
                                                            if(edit==1){
                                                                m.st.executeUpdate("UPDATE employee SET epfNo='"+e_epfno+"', fname='"+e_fname+"', lname='"+e_lname+"', gender='"+e_gender+"', email='"+e_email+"', phone='"+e_phone+"', address='"+e_address+"', dob='"+e_dob+"', nic='"+e_nic+"', jdate='"+e_jdate+"', user_level='"+e_ul+"' WHERE empNo='"+primary_key+"'");
                                                                if(imgPath.getText() != null){m.saveImage(e_epfno);}
                                                                m.dynamicTable(l.jTextField1, l.jComboBox1, l.pageNo, l.jTable1, "employee");
                                                            }
                                                            else{
                                                                m.st.executeUpdate("INSERT INTO employee (epfNo, fname, lname, gender, email, phone, address, dob, nic, jdate, user_level, username, password) VALUES ('"+e_epfno+"', '"+e_fname+"', '"+e_lname+"', '"+e_gender+"', '"+e_email+"', '"+e_phone+"', '"+e_address+"', '"+e_dob+"', '"+e_nic+"', '"+e_jdate+"', '"+e_ul+"', '"+e_epfno+"', '"+pwd+"')");
                                                                if(imgPath.getText() != null){m.saveImage(e_epfno);}
                                                                m.dynamicTable(l.jTextField1, l.jComboBox1, l.pageNo, l.jTable1, "employee");
                                                            }
                                                            ResultSet rs2= m.st.executeQuery("select MAX(empNo) from employee");
                                                            rs2.next();
                                                            if(edit!=1){
                                                                JOptionPane.showMessageDialog(null, "successfully added !\nemployee id ="+rs2.getString(1));
                                                                this.dispose();
                                                                new addEmployee().setVisible(true);
                                                            }else{
                                                                JOptionPane.showMessageDialog(null, "successfully updated.");
                                                                this.dispose();
                                                            }
                                                        }
                                                        } catch (SQLException ex) {
                                                            Logger.getLogger(addSupplier.class.getName()).log(Level.SEVERE, null, ex);
                                                        }
                                                    
                                            
                                                }else {
                                                    nic.setBorder(BorderFactory.createLineBorder (Color.red));
                                                    if(e_nic.equals("")){
                                                        error.setText("NIC No field cannot be empty !");
                                                    }
                                                }
                                            }
                                        }else {address.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Address field cannot be empty !");}
                                    //}else {phone.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Phone field cannot be empty !");}
                                    }else{
                                            phonecheck=1;
                                            phone.setBorder(BorderFactory.createLineBorder (Color.red));
                                            phone.setForeground(Color.red);
                                        }
                                }else{
                                        emailcheck=1;
                                        email.setBorder(BorderFactory.createLineBorder (Color.red));
                                        email.setForeground(Color.red);
                                        email.setBorder(BorderFactory.createLineBorder (Color.red));
                                        error.setText("Invalid email address !");

                                    }
                            }else {name1.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Last Name field cannot be empty !");}
                        }else {name.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("First Name field cannot be empty !");}
                    }
                }else{
                    epfNo.setBorder(BorderFactory.createLineBorder (Color.red));
                    if(e_epfno.equals("")){
                        error.setText("EPF No field cannot be empty !");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {epfNo.setBorder(BorderFactory.createLineBorder (Color.red));error.setText("Invalid EPF Number !");}
    }//GEN-LAST:event_addCustomerActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if(emailcheck==1){
            email.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
            email.setForeground(Color.black);
            email.setText("");
            emailcheck=0;
        }
        error.setText(null);
        phone.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        phone.setForeground(Color.black);
    }//GEN-LAST:event_emailFocusGained

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        /*if(phonecheck==1){
        phone.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        phone.setForeground(Color.black);
        phone.setText("");
        phonecheck=0;
        }*/
        phone.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        phone.setForeground(Color.black);
    }//GEN-LAST:event_phoneFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        m.getFileName(img, imgPath);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void epfNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_epfNoFocusGained
        epfNo.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        epfNo.setForeground(Color.black);
        error.setText(null);
    }//GEN-LAST:event_epfNoFocusGained

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        name.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        name.setForeground(Color.black);
        error.setText(null);
    }//GEN-LAST:event_nameFocusGained

    private void name1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name1FocusGained
        name1.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        name1.setForeground(Color.black);
        error.setText(null);
    }//GEN-LAST:event_name1FocusGained

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        address.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        address.setForeground(Color.black);
        error.setText(null);
    }//GEN-LAST:event_addressFocusGained

    private void dobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobFocusGained
        dob.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        dob.setForeground(Color.black);
        error.setText(null);
    }//GEN-LAST:event_dobFocusGained

    private void nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusGained
        nic.setBorder(BorderFactory.createLineBorder (Color.decode("#808080")));
        nic.setForeground(Color.black);
        error.setText(null);
    }//GEN-LAST:event_nicFocusGained

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void epfNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epfNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epfNoActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    protected javax.swing.JButton addCustomer;
    private javax.swing.JTextField address;
    private org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField epfNo;
    protected javax.swing.JLabel error;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel img;
    private javax.swing.JLabel imgPath;
    protected javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    protected javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    protected javax.swing.JLabel jLabel17;
    protected javax.swing.JLabel jLabel18;
    protected javax.swing.JLabel jLabel19;
    protected javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    protected javax.swing.JLabel jLabel21;
    protected javax.swing.JLabel jLabel22;
    protected javax.swing.JLabel jLabel23;
    protected javax.swing.JLabel jLabel24;
    protected javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
