/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITP;

import static ITP.Home.chemical;
import static ITP.Home.dsb;
import inventory.dbCon;
import static inventory.dbCon.con;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import shanuka.viewChemicals;

/**
 *
 * @author Ranmal
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();

        jTable1.setGridColor(Color.WHITE);
        jTable1.setForeground(Color.WHITE);
        jTable1.setOpaque(false);
        ((DefaultTableCellRenderer) jTable1.getDefaultRenderer(Object.class)).setBackground(new Color(0, 0, 0, 0));
        jScrollPane1.getViewport().setOpaque(false);
        jTable1.setShowGrid(true);

        updateDB();
        chemNotify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        att = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mac = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ve = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(940, 480));
        setMinimumSize(new java.awt.Dimension(940, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 220, 300));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Dash1.png"))); // NOI18N
        jLabel5.setText("jLabel4");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, 130));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Current Process Status :-");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, 20));

        att.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        att.setForeground(new java.awt.Color(255, 255, 255));
        add(att, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 70, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Dash6.png"))); // NOI18N
        jLabel19.setText("jLabel4");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 130, 130));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Machines to be Repaired :-");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 150, 20));

        mac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mac.setForeground(new java.awt.Color(255, 255, 255));
        add(mac, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 70, 20));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Dash7.png"))); // NOI18N
        jLabel22.setText("jLabel4");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 130, 130));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Today's Employee Attendance :-");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 180, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Critical Level Chemical Stocks");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 220, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Vehicles Available :-");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 150, 20));

        ve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ve.setForeground(new java.awt.Color(255, 255, 255));
        add(ve, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 730, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DASHBOARD");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 390, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Dashboard.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Dash4.png"))); // NOI18N
        jLabel25.setText("jLabel4");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 130, 130));

        jSeparator2.setForeground(new java.awt.Color(248, 65, 65));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 210, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/IMG-20180315-WA0017.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(940, 480));
        jLabel1.setMinimumSize(new java.awt.Dimension(940, 480));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        try {
            pieChart1 p1 = new pieChart1();

            ResultSet rs = dbCon.con.createStatement().executeQuery("SELECT COUNT(*) as count FROM listaqlandfb WHERE AQL !=1");
            rs.next();
            int un = rs.getInt("count");
            rs = dbCon.con.createStatement().executeQuery("SELECT COUNT(*) as count FROM processplan WHERE BLP_No is not NULL and Finished=0");
            rs.next();
            int pr = rs.getInt("count");
            rs = dbCon.con.createStatement().executeQuery("SELECT COUNT(*) as count FROM processplan WHERE BLP_No is not NULL and Finished=1");
            rs.next();
            int fi = rs.getInt("count");

            double pun, ppr, pfi;

            pun = (un * 100.0 / (un + pr + fi));
            ppr = (pr * 100.0 / (un + pr + fi));
            pfi = (fi * 100.0 / (un + pr + fi));

            DefaultPieDataset pieDataset = new DefaultPieDataset();
            pieDataset.setValue("Unprocessed", pun);
            pieDataset.setValue("Processing", ppr);
            pieDataset.setValue("Finished", pfi);
            JFreeChart chart = ChartFactory.createPieChart("Current Process Status", pieDataset, true, true, true);
            PiePlot p = (PiePlot) chart.getPlot();

            ChartPanel frame = new ChartPanel(chart, 400, 300, 400, 300, 400, 300, true, true, true, true, true, true);

            frame.setSize(400, 300);
            GridBagLayout layout = new GridBagLayout();

            p1.jPanel1.setLayout(layout);
            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 0;
            c.gridy = 0;
            p1.jPanel1.add(frame, c);
            p1.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        try {
            // TODO add your handling code here:
            pieChart1 p1 = new pieChart1();
            ResultSet rs = dbCon.con.createStatement().executeQuery("SELECT COUNT(*) as count FROM employee");
            rs.next();
            int tot = rs.getInt("count");
            rs = dbCon.con.createStatement().executeQuery("SELECT COUNT(*) as count FROM attendance WHERE today=1");
            rs.next();
            int pr = rs.getInt("count");
            
            int ab = tot - pr;

            double pab, ppr;
            pab = (ab * 100.0 / (ab + pr));
            ppr = (pr * 100.0 / (ab + pr));

            DefaultPieDataset pieDataset = new DefaultPieDataset();
            pieDataset.setValue("Present", ppr);
            pieDataset.setValue("Absent", pab);

            JFreeChart chart = ChartFactory.createPieChart("Today's Employee Attendance", pieDataset, true, true, true);
            PiePlot p = (PiePlot) chart.getPlot();
            ChartPanel frame = new ChartPanel(chart, 400, 300, 400, 300, 400, 300, true, true, true, true, true, true);
            //frame.setSize(400, 300);
            GridBagLayout layout = new GridBagLayout();
            p1.jPanel1.setLayout(layout);
            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 0;
            c.gridy = 0;
            p1.jPanel1.add(frame, c);
            p1.setVisible(true);

            att.setText(Integer.toString(pr));

        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        Home.dynaDisplay(chemical);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel att;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mac;
    private javax.swing.JLabel ve;
    // End of variables declaration//GEN-END:variables

    void updateDB() {
        ResultSet rs;
        try {
            rs = dbCon.con.createStatement().executeQuery("SELECT COUNT(*) as count FROM attendance WHERE today=1");
            rs.next();
            att.setText(rs.getString("count"));

            rs = dbCon.con.createStatement().executeQuery("SELECT COUNT(*) as count FROM vehicle");
            rs.next();
            ve.setText(rs.getString("count"));

            rs = dbCon.con.createStatement().executeQuery("SELECT COUNT(*) as count FROM repair where status !='Available'");
            rs.next();
            mac.setText(rs.getString("count"));
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void chemNotify() {
        try {
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM chemical");

            DefaultTableModel model = new DefaultTableModel(new Object[]{"chemical", "name", "quantity"}, 0);
            while (rs.next()) {
                if (rs.getInt("qty")<750) {
                    String ch = rs.getString("chemical");
                    String na = rs.getString("name");
                    String qt = rs.getString("qty");
                    Object[] row = {ch, na, qt};
                    model.addRow(row);
                }
            }
            jTable1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(viewChemicals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
