/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITP;

import static inventory.dbCon.con;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Ranmal
 */
public class EditPwd extends javax.swing.JPanel {

    /**
     * Creates new form EditPwd
     */
    public EditPwd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        new2 = new javax.swing.JPasswordField();
        current = new javax.swing.JPasswordField();
        new1 = new javax.swing.JPasswordField();
        new1l = new javax.swing.JLabel();
        new2l = new javax.swing.JLabel();
        currentl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(940, 480));
        setMinimumSize(new java.awt.Dimension(940, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 920, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("CHANGE PASSWORD");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 390, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/changePW.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Current Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("New Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 200, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Confirm New Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 180, 40));

        jButton4.setBackground(new java.awt.Color(240, 14, 19));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 40));

        jButton5.setBackground(new java.awt.Color(15, 195, 15));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Change.png"))); // NOI18N
        jButton5.setText("Change");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 120, 40));

        new2.setBackground(new java.awt.Color(240, 240, 240));
        new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new2ActionPerformed(evt);
            }
        });
        add(new2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 260, 40));

        current.setBackground(new java.awt.Color(240, 240, 240));
        add(current, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 260, 40));

        new1.setBackground(new java.awt.Color(240, 240, 240));
        add(new1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 260, 40));

        new1l.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        new1l.setForeground(new java.awt.Color(255, 0, 0));
        add(new1l, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 210, 280, 40));

        new2l.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        new2l.setForeground(new java.awt.Color(255, 0, 0));
        add(new2l, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 270, 280, 40));

        currentl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        currentl.setForeground(new java.awt.Color(255, 0, 0));
        add(currentl, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 150, 280, 40));

        jLabel1.setPreferredSize(new java.awt.Dimension(940, 480));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        current.setText("");
        new1.setText("");
        new2.setText("");
        Home.ep.setVisible(false);
        Home.dsb.setVisible(true);
        currentl.setText(null);
        new1l.setText(null);
        new2l.setText(null);
        current.setBorder(BorderFactory.createLineBorder(Color.decode("#A0A0A0")));
        new1.setBorder(BorderFactory.createLineBorder(Color.decode("#A0A0A0")));
        new2.setBorder(BorderFactory.createLineBorder(Color.decode("#A0A0A0")));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new2ActionPerformed
        // TODO add your handling code here:
        change();
    }//GEN-LAST:event_new2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        change();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField current;
    private javax.swing.JLabel currentl;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField new1;
    private javax.swing.JLabel new1l;
    private javax.swing.JPasswordField new2;
    private javax.swing.JLabel new2l;
    // End of variables declaration//GEN-END:variables

    private boolean changeVal() throws SQLException {
        if (current.getText().equals("")) {
            currentl.setText("please enter the current password");
            current.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
            return false;
        } else {
            if (new1.getText().equals("")) {
                new1l.setText("please enter the new password");
                new1.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                return false;
            } else {
                if (new2.getText().equals("")) {
                    new2l.setText("please confirm the new password");
                    new2.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                    return false;
                } else {
                    if (new1.getText().equals(new2.getText())) {
                        ResultSet rs = con.createStatement().executeQuery("SELECT password FROM employee WHERE username = '" + Home.user + "'");
                        rs.next();
                        int i = current.getText().hashCode();
                        if (i == rs.getInt("password")) {
                            if (current.getText().equals(new1.getText())) {
                                new1l.setText("current password cannot be new password");
                                new1.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                                return false;
                            } else {
                                ResultSet pw = con.createStatement().executeQuery("SELECT nic FROM employee WHERE username = '" + Home.user + "'");
                                pw.next();
                                if (new1.getText().equals(pw.getString("nic"))) {
                                    new1l.setText("cannot use NIC as new password");
                                    new1.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                                    return false;
                                } else {
                                    return true;
                                }
                            }
                        } else {
                            currentl.setText("incorrect password");
                            current.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                            return false;
                        }
                    } else {
                        new2l.setText("confirm password does not match");
                        new2.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                        return false;
                    }
                }
            }
        }
    }

    private void change() {
        currentl.setText(null);
        new1l.setText(null);
        new2l.setText(null);
        current.setBorder(BorderFactory.createLineBorder(Color.decode("#A0A0A0")));
        new1.setBorder(BorderFactory.createLineBorder(Color.decode("#A0A0A0")));
        new2.setBorder(BorderFactory.createLineBorder(Color.decode("#A0A0A0")));
        try {
            // TODO add your handling code here:
            if (changeVal()) {
                con.prepareStatement("UPDATE employee SET password ='" + new2.getText().hashCode() + "' WHERE username = '" + Home.user + "'").execute();
                JOptionPane.showMessageDialog(null, "password updated", "Done", JOptionPane.INFORMATION_MESSAGE);
                current.setText("");
                new1.setText("");
                new2.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditPwd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
