/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITP;

import inventory.dbCon;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Ranmal
 */
public class GloveView extends javax.swing.JPanel {

    /**
     * Creates new form GloveView
     */
    int tot;
    int maxPages;
    int pg = 1;
    int lim = 15;
    int offset = 0;

    public GloveView() {

        initComponents();
        AutoCompleteDecorator.decorate(jComboBox1);

        jButton9.setVisible(false);
        jButton8.setVisible(false);
/*
        //Table Transparent
        //FabricPackingList.setBackground(new Color (0,0,0,0));
        //((DefaultTableCellRenderer)FabricPackingList.getDefaultRenderer(Object.class)).setBackground(new Color (0,0,0,0));
        GlovePackingList.setGridColor(Color.WHITE);

        GlovePackingList.setForeground(Color.WHITE);

        //jScrollPane1.setBackground(new Color (0,0,0,0));
        //jScrollPane1.setOpaque(false);
        GlovePackingList.setOpaque(false);

        ((DefaultTableCellRenderer) GlovePackingList.getDefaultRenderer(Object.class)).setBackground(new Color(0, 0, 0, 0));

        jScrollPane1.getViewport().setOpaque(false);

        GlovePackingList.setShowGrid(true);

        //End
        */
        dbCon d = new dbCon();
        d.connect();

        updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");

    }

    void updateMax(String q, javax.swing.JLabel tox, javax.swing.JTextField pad) {
        try {
            ResultSet rs = dbCon.con.createStatement().executeQuery(q);
            rs.next();
            tot = rs.getInt("count");

            int i = tot % lim;
            if (i > 0) {
                maxPages = tot / lim + 1;
            } else {
                maxPages = tot / lim;
            }
            tox.setText(Integer.toString(maxPages));

            if (pg > maxPages) {
                pg = maxPages;
                pad.setText(Integer.toString(pg));
                if (pg == 0) {
                    offset = (pg) * lim;
                } else {
                    offset = (pg - 1) * lim;
                }
            }
            if (maxPages == 1) {
                pg = 1;
                pad.setText(Integer.toString(pg));
                if (pg == 0) {
                    offset = (pg) * lim;
                } else {
                    offset = (pg - 1) * lim;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(GloveView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void addToTable(String query) {

        try {
            ResultSet rs = dbCon.con.createStatement().executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) GlovePackingList.getModel();

            model.getDataVector().removeAllElements();

            while (rs.next()) {
                String bn = rs.getString("lotNo");
                String date = rs.getString("pktDate");
                String pln = rs.getString("pktListNo");
                String cus = rs.getString("customer");
                String style = rs.getString("style");
                String size = rs.getString("size");
                String lots = rs.getString("lots");
                String tq = rs.getString("totQtyPrs");
                String tkg = rs.getString("totKg");
                String emp = rs.getString("empNo");

                Object[] rowData = {bn, date, pln, cus, style, size, lots, tq, tkg, emp};
                model.addRow(rowData);
            }

            GlovePackingList.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(GloveView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        GlovePackingList = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(940, 480));
        setMinimumSize(new java.awt.Dimension(940, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(71, 71, 116));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Print.png"))); // NOI18N
        jButton10.setText("Print");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 90, 30));

        jButton9.setBackground(new java.awt.Color(0, 0, 150));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Edit.png"))); // NOI18N
        jButton9.setText("Edit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 100, 30));

        jButton8.setBackground(new java.awt.Color(240, 14, 19));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Delete.png"))); // NOI18N
        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 100, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 150));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Add.png"))); // NOI18N
        jButton5.setText("Add New Glove");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 150, 30));

        jButton4.setBackground(new java.awt.Color(15, 195, 15));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Refresh.png"))); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 100, 30));

        jButton3.setBackground(new java.awt.Color(219, 76, 13));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Back.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 90, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField1.setText("SEARCH.......");
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 920, 10));

        GlovePackingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot No", "Date", "Packing List No", "Customer", "Style #", "Size", "Lots", "Total Qty", "Total Kg", "Emp No"
            }
        ));
        GlovePackingList.setMaximumSize(new java.awt.Dimension(220, 175));
        GlovePackingList.setMinimumSize(new java.awt.Dimension(220, 175));
        GlovePackingList.setName(""); // NOI18N
        GlovePackingList.setRowHeight(35);
        GlovePackingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GlovePackingListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GlovePackingList);
        if (GlovePackingList.getColumnModel().getColumnCount() > 0) {
            GlovePackingList.getColumnModel().getColumn(0).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(0).setPreferredWidth(5);
            GlovePackingList.getColumnModel().getColumn(1).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(1).setPreferredWidth(5);
            GlovePackingList.getColumnModel().getColumn(2).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(2).setPreferredWidth(32);
            GlovePackingList.getColumnModel().getColumn(3).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(3).setPreferredWidth(100);
            GlovePackingList.getColumnModel().getColumn(4).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(4).setPreferredWidth(10);
            GlovePackingList.getColumnModel().getColumn(5).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(5).setPreferredWidth(5);
            GlovePackingList.getColumnModel().getColumn(6).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(6).setPreferredWidth(5);
            GlovePackingList.getColumnModel().getColumn(7).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(7).setPreferredWidth(10);
            GlovePackingList.getColumnModel().getColumn(8).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(8).setPreferredWidth(10);
            GlovePackingList.getColumnModel().getColumn(9).setResizable(false);
            GlovePackingList.getColumnModel().getColumn(9).setPreferredWidth(10);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 920, 200));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, 20));

        jButton1.setBackground(new java.awt.Color(71, 71, 116));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Previous.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 30, 30));

        jButton2.setBackground(new java.awt.Color(71, 71, 116));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/First.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 30, 30));

        jButton6.setBackground(new java.awt.Color(71, 71, 116));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Next.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 30, 30));

        jButton7.setBackground(new java.awt.Color(71, 71, 116));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Last.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 30, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Entries");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 40, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Show");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 30, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GLOVE PACKING LISTS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("4");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/IMG-20180315-WA0017.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new NewGlovesPL().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Home.gv.setVisible(false);
        //Home.dsb.setVisible(false);
        //Home.fv.setVisible(false);
        //Home.gav.setVisible(false);
        //Home.po.setVisible(false);
        Home.spl.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int r = GlovePackingList.getSelectedRow();
        String data;
        data = GlovePackingList.getValueAt(r, 0).toString();
        new NewGlovesPL(true, data).setVisible(true);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int r = GlovePackingList.getSelectedRow();
        String data;
        data = GlovePackingList.getValueAt(r, 0).toString();
        int retValue = JOptionPane.showConfirmDialog(Home.gv, "Do You Want to Delete Lot Number " + data + " ???", "DELETE", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);

        if (retValue == 0) {

            try {
                dbCon.con.prepareStatement("DELETE FROM splglove WHERE lotNo ='" + data + "'").execute();
                dbCon.con.prepareStatement("DELETE FROM poglove WHERE lotNo ='" + data + "'").execute();
                dbCon.con.prepareStatement("DELETE FROM listaqlandfb WHERE BLP_No ='" + data + "'").execute();

                JOptionPane.showMessageDialog(jLabel1, "Batch Number Deleted Successfully", "Done", JOptionPane.INFORMATION_MESSAGE);
                updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
                addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
            } catch (SQLException ex) {
                Logger.getLogger(GloveView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText("SEARCH.......");
        updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void GlovePackingListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GlovePackingListMouseClicked
        jButton9.setVisible(true);
        jButton8.setVisible(true);
    }//GEN-LAST:event_GlovePackingListMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pg = 1;
        jTextField2.setText(Integer.toString(pg));
        if (pg == 0) {
            offset = (pg) * lim;
        } else {
            offset = (pg - 1) * lim;
        }

        updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (pg > 1) {
            pg--;
            jTextField2.setText(Integer.toString(pg));
        }
        if (pg == 0) {
            offset = (pg) * lim;
        } else {
            offset = (pg - 1) * lim;
        }

        updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        int p = Integer.parseInt((String) jTextField2.getText());
        if (p > maxPages || p < 1) {
        } else {

            pg = p;
            if (pg == 0) {
                offset = (pg) * lim;
            } else {
                offset = (pg - 1) * lim;
            }

            updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
            addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");

        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (pg < maxPages) {
            pg++;
            jTextField2.setText(Integer.toString(pg));
        }
        if (pg == 0) {
            offset = (pg) * lim;
        } else {
            offset = (pg - 1) * lim;
        }
        updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        pg = maxPages;
        jTextField2.setText(Integer.toString(pg));
        if (pg == 0) {
            offset = (pg) * lim;
        } else {
            offset = (pg - 1) * lim;
        }

        updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().equals("")) {
            lim = 15;
            jComboBox1.setSelectedItem("15");
            pg = 1;
            jTextField2.setText(Integer.toString(pg));
            if (pg == 0) {
                offset = (pg) * lim;
            } else {
                offset = (pg - 1) * lim;
            }
            updateMax("SELECT COUNT(*) AS count FROM splgarment WHERE AQL_FB_Status =0", jLabel7, jTextField2);
            addToTable("SELECT * FROM splgarment WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
        } else {
            lim = Integer.parseInt((String) jComboBox1.getSelectedItem());
            pg = 1;
            jTextField2.setText(Integer.toString(pg));
            if (pg == 0) {
                offset = (pg) * lim;
            } else {
                offset = (pg - 1) * lim;
            }
            updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
            addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Home.Report(GlovePackingList, "Gloves Packing List","E:\\Reports\\glovePktList.pdf");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
       String sh = jTextField1.getText();
        if (sh.equals("")) {
           updateMax("SELECT COUNT(*) AS count FROM splglove WHERE AQL_FB_Status =0", jLabel7, jTextField2);
            addToTable("SELECT * FROM splglove WHERE AQL_FB_Status =0 LIMIT " + lim + " OFFSET " + offset + "");
        } else {

            addToTable("SELECT * FROM splglove WHERE lotNo like '%" + sh + "%' or pktDate like '%" + sh + "%' or pktListNo like '%" + sh + "%' or customer like '%" + sh + "%' or style like '%" + sh + "%' or size like '%" + sh + "%' or lots like '%" + sh + "%' or totQtyPrs like '%" + sh + "%' or totKg like '%" + sh + "%' or empNo like '%" + sh + "%'");

        }
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText(null);
    }//GEN-LAST:event_jTextField1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GlovePackingList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
