package ITP;


import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vimukthi
 */
public class NewJFrame extends javax.swing.JFrame {

    GridBagLayout l = new GridBagLayout();
    listEmployees le;
    listSuppliers ls;
    listCustomers lc;
    addEmployee ae;
    addCustomer ac;
    addSupplier as;
    bestEmployee be;
    
    public NewJFrame() {
        initComponents();
        le = new listEmployees();
        ls = new listSuppliers();
        lc = new listCustomers();
        ae = new addEmployee();
        ac = new addCustomer();
        as = new addSupplier();
        be = new bestEmployee();
        
        jPanel2.setLayout(l);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx =0;
        c.gridy =0;
        jPanel2.add(le, c);
        c.gridx =0;
        c.gridy =0;
        jPanel2.add(ls, c);
        c.gridx =0;
        c.gridy =0;
        jPanel2.add(lc, c);
        c.gridx =0;
        c.gridy =0;
        jPanel2.add(be, c);
        
        /*c.gridx =0;
        c.gridy =0;
        jPanel2.add(ac, c);
        c.gridx =0;
        c.gridy =0;
        jPanel2.add(as, c);*/
        
        le.setVisible(false);
        ls.setVisible(false);
        lc.setVisible(false);
        ae.setVisible(false);
        as.setVisible(false);
        ac.setVisible(false);
        be.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        listEmp = new javax.swing.JButton();
        listCust = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(10, 24, 224));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/icons8-customer-40 (3).png"))); // NOI18N
        jButton1.setText("<html><center>Add<br />Customer</center><html>");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(73, 67));
        jButton1.setMinimumSize(new java.awt.Dimension(73, 67));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jButton4.setBackground(new java.awt.Color(10, 24, 224));
        jButton4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/addSupplier.png"))); // NOI18N
        jButton4.setText("<html><center>Add<br />Supplier</center><html>");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jButton5.setBackground(new java.awt.Color(10, 24, 224));
        jButton5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/leaderBoard.png"))); // NOI18N
        jButton5.setText("<html><center>Employee<br />Of<br />The Month</center><html>");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        listEmp.setBackground(new java.awt.Color(10, 24, 224));
        listEmp.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        listEmp.setForeground(new java.awt.Color(255, 255, 255));
        listEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/viewEmployees.png"))); // NOI18N
        listEmp.setText("<html><center>List<br />Employee</center><html>");
        listEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listEmp.setPreferredSize(new java.awt.Dimension(100, 100));
        listEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEmpActionPerformed(evt);
            }
        });
        jPanel1.add(listEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        listCust.setBackground(new java.awt.Color(10, 24, 224));
        listCust.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        listCust.setForeground(new java.awt.Color(255, 255, 255));
        listCust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/icons8-customer-40 (2).png"))); // NOI18N
        listCust.setText("<html><center>List<br />Customer</center><html>");
        listCust.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listCust.setPreferredSize(new java.awt.Dimension(100, 100));
        listCust.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCustActionPerformed(evt);
            }
        });
        jPanel1.add(listCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jButton2.setBackground(new java.awt.Color(10, 24, 224));
        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/addEmployee.png"))); // NOI18N
        jButton2.setText("<html><center>Add<br />Employee</center><html>");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jButton6.setBackground(new java.awt.Color(10, 24, 224));
        jButton6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/viewSuppliers.png"))); // NOI18N
        jButton6.setText("<html><center>List<br />Supplier</center><html>");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/back.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 480));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(940, 480));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 940, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ac.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        ae.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCustActionPerformed
        jPanel1.setVisible(false);
        lc.setVisible(true);
    }//GEN-LAST:event_listCustActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        as.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel1.setVisible(false);
        be.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void listEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEmpActionPerformed
        jPanel1.setVisible(false);
        le.setVisible(true);
    }//GEN-LAST:event_listEmpActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel1.setVisible(false);
        ls.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton listCust;
    private javax.swing.JButton listEmp;
    // End of variables declaration//GEN-END:variables
}
