/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITP;

import static ITP.Home.att;

/**
 *
 * @author Axio
 */
public class people extends javax.swing.JPanel {

    /**
     * Creates new form people
     */
    
    public people() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        attendance = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        listEmp = new javax.swing.JButton();
        listCust = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(940, 480));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendance.setBackground(new java.awt.Color(48, 48, 240));
        attendance.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        attendance.setForeground(new java.awt.Color(255, 255, 255));
        attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/viewsize.png"))); // NOI18N
        attendance.setText("<html><center>Attendance<br />Management</center><html>");
        attendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        attendance.setPreferredSize(new java.awt.Dimension(100, 100));
        attendance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceActionPerformed(evt);
            }
        });
        jPanel1.add(attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 120, 120));

        jButton1.setBackground(new java.awt.Color(48, 48, 240));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/icons8-customer-40 (3).png"))); // NOI18N
        jButton1.setText("<html><center>Add<br />Customer</center><html>");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(73, 67));
        jButton1.setMinimumSize(new java.awt.Dimension(73, 67));
        jButton1.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jButton4.setBackground(new java.awt.Color(48, 48, 240));
        jButton4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/addSupplier.png"))); // NOI18N
        jButton4.setText("<html><center>Add<br />Supplier</center><html>");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jButton5.setBackground(new java.awt.Color(48, 48, 240));
        jButton5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/leaderBoard.png"))); // NOI18N
        jButton5.setText("<html><center>Employee<br />Of<br />The Month</center><html>");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 120, 120));

        listEmp.setBackground(new java.awt.Color(48, 48, 240));
        listEmp.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        listEmp.setForeground(new java.awt.Color(255, 255, 255));
        listEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/viewEmployees.png"))); // NOI18N
        listEmp.setText("<html><center>List<br />Employee</center><html>");
        listEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listEmp.setPreferredSize(new java.awt.Dimension(120, 120));
        listEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEmpActionPerformed(evt);
            }
        });
        jPanel1.add(listEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        listCust.setBackground(new java.awt.Color(48, 48, 240));
        listCust.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        listCust.setForeground(new java.awt.Color(255, 255, 255));
        listCust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/icons8-customer-40 (2).png"))); // NOI18N
        listCust.setText("<html><center>List<br />Customer</center><html>");
        listCust.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listCust.setPreferredSize(new java.awt.Dimension(120, 120));
        listCust.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCustActionPerformed(evt);
            }
        });
        jPanel1.add(listCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jButton2.setBackground(new java.awt.Color(48, 48, 240));
        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/addEmployee.png"))); // NOI18N
        jButton2.setText("<html><center>Add<br />Employee</center><html>");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jButton6.setBackground(new java.awt.Color(48, 48, 240));
        jButton6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/images/viewSuppliers.png"))); // NOI18N
        jButton6.setText("<html><center>List<br />Supplier</center><html>");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMaximumSize(new java.awt.Dimension(120, 120));
        jButton6.setMinimumSize(new java.awt.Dimension(120, 120));
        jButton6.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PEOPLE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 390, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/People.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 680, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/IMG-20180315-WA0017.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new addCustomer().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        new addSupplier().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Home.peo.setVisible(false);
        Home.be.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void listEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEmpActionPerformed
        Home.peo.setVisible(false);
        Home.le.setVisible(true);
    }//GEN-LAST:event_listEmpActionPerformed

    private void listCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCustActionPerformed
        Home.peo.setVisible(false);
        Home.lc.setVisible(true);
    }//GEN-LAST:event_listCustActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new addEmployee().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Home.peo.setVisible(false);
        Home.ls.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceActionPerformed
        Home.peo.setVisible(false);
        att.setVisible(true);
    }//GEN-LAST:event_attendanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton listCust;
    private javax.swing.JButton listEmp;
    // End of variables declaration//GEN-END:variables
}
