/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITP;

import inventory.dbCon;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Ranmal
 */
public class POFabricView extends javax.swing.JPanel {

    /**
     * Creates new form POFabricView
     */
    int tot;
    int maxPages;
    int pg = 1;
    int lim = 15;
    int offset = 0;

    public POFabricView() {
        initComponents();
        AutoCompleteDecorator.decorate(jComboBox1);

        jButton9.setVisible(false);
        jButton8.setVisible(false);
/*
        //Table Transparent
        FabricPO.setGridColor(Color.WHITE);

        FabricPO.setForeground(Color.WHITE);

        FabricPO.setOpaque(false);

        ((DefaultTableCellRenderer) FabricPO.getDefaultRenderer(Object.class)).setBackground(new Color(0, 0, 0, 0));

        jScrollPane1.getViewport().setOpaque(false);

        FabricPO.setShowGrid(true);

        //End
        */
        dbCon d = new dbCon();
        d.connect();

        updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");

    }

    void updateMax(String q, javax.swing.JLabel tox, javax.swing.JTextField pad) {
        try {
            ResultSet rs = dbCon.con.createStatement().executeQuery(q);
            rs.next();
            tot = rs.getInt("count");

            int i = tot % lim;
            if (i > 0) {
                maxPages = tot / lim + 1;
            } else {
                maxPages = tot / lim;
            }
            tox.setText(Integer.toString(maxPages));

            if (pg > maxPages) {
                pg = maxPages;
                pad.setText(Integer.toString(pg));
                if (pg == 0) {
                    offset = (pg) * lim;
                } else {
                    offset = (pg - 1) * lim;
                }
            }
            if (maxPages == 1) {
                pg = 1;
                pad.setText(Integer.toString(pg));
                if (pg == 0) {
                    offset = (pg) * lim;
                } else {
                    offset = (pg - 1) * lim;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(POFabricView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void addToTable(String query) {

        try {
            ResultSet rs = dbCon.con.createStatement().executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) FabricPO.getModel();

            model.getDataVector().removeAllElements();

            while (rs.next()) {
                String bn = rs.getString("p.batchNo");
                String pd = rs.getString("poDate");
                String ed = rs.getString("expDate");
                String cus = rs.getString("customer");
                String po = rs.getString("poNo");
                String tlm = rs.getString("totLenMeters");
                String tc = rs.getString("totCost");

                Object[] rowData = {pd, ed, po, cus, bn, tlm, tc};
                model.addRow(rowData);
            }

            FabricPO.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(POFabricView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        FabricPO = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(940, 480));
        setMinimumSize(new java.awt.Dimension(940, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FABRIC PURCHASE ORDERS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 40));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField1.setText("SEARCH.......");
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Show");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 30, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Entries");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 40, 20));

        jButton4.setBackground(new java.awt.Color(15, 195, 15));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Refresh.png"))); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 100, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 150));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Add.png"))); // NOI18N
        jButton5.setText("Add Fabric PO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 150, 30));

        jButton3.setBackground(new java.awt.Color(219, 76, 13));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Back.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 90, 30));

        jButton10.setBackground(new java.awt.Color(71, 71, 116));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Print.png"))); // NOI18N
        jButton10.setText("Print");
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 90, 30));

        jButton8.setBackground(new java.awt.Color(240, 14, 19));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Delete.png"))); // NOI18N
        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 100, 30));

        jButton9.setBackground(new java.awt.Color(0, 0, 150));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Edit.png"))); // NOI18N
        jButton9.setText("Edit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 100, 30));

        jButton7.setBackground(new java.awt.Color(71, 71, 116));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Last.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 30, 30));

        jButton6.setBackground(new java.awt.Color(71, 71, 116));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Next.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 30, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 30, 30));

        jButton1.setBackground(new java.awt.Color(71, 71, 116));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Previous.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 30, 30));

        jButton2.setBackground(new java.awt.Color(71, 71, 116));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/First.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 30, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 920, 10));

        FabricPO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Exp Date", "PO #", "Customer", "Batch No", "Total (m)", "Total Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FabricPO.setMaximumSize(new java.awt.Dimension(220, 175));
        FabricPO.setMinimumSize(new java.awt.Dimension(220, 175));
        FabricPO.setName(""); // NOI18N
        FabricPO.setRowHeight(35);
        FabricPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FabricPOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FabricPO);
        if (FabricPO.getColumnModel().getColumnCount() > 0) {
            FabricPO.getColumnModel().getColumn(0).setResizable(false);
            FabricPO.getColumnModel().getColumn(0).setPreferredWidth(5);
            FabricPO.getColumnModel().getColumn(1).setResizable(false);
            FabricPO.getColumnModel().getColumn(1).setPreferredWidth(5);
            FabricPO.getColumnModel().getColumn(2).setResizable(false);
            FabricPO.getColumnModel().getColumn(2).setPreferredWidth(10);
            FabricPO.getColumnModel().getColumn(3).setResizable(false);
            FabricPO.getColumnModel().getColumn(3).setPreferredWidth(150);
            FabricPO.getColumnModel().getColumn(4).setResizable(false);
            FabricPO.getColumnModel().getColumn(4).setPreferredWidth(10);
            FabricPO.getColumnModel().getColumn(5).setResizable(false);
            FabricPO.getColumnModel().getColumn(5).setPreferredWidth(10);
            FabricPO.getColumnModel().getColumn(6).setResizable(false);
            FabricPO.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 920, 200));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("4");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/IMG-20180315-WA0017.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(940, 480));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new NewPOFabric().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Home.fpo.setVisible(false);
        Home.po.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int r = FabricPO.getSelectedRow();
        String data;
        String data2;

        data = FabricPO.getValueAt(r, 2).toString();
        data2 = FabricPO.getValueAt(r, 4).toString();

        int retValue = JOptionPane.showConfirmDialog(Home.fpo, "Do You Want to Delete Purchase Order Number " + data + " ???", "DELETE", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);

        int po = Integer.parseInt(data);

        if (retValue == 0) {

            try {
                dbCon.con.prepareStatement("DELETE FROM pofabric WHERE poNo =" + po + "").execute();
                dbCon.con.prepareStatement("UPDATE splfabric SET PO_Status=0 WHERE batchNo ='" + data2 + "'").execute();

                JOptionPane.showMessageDialog(jLabel1, "Purchase Order Number Deleted Successfully", "Done", JOptionPane.INFORMATION_MESSAGE);
                updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
                addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");

            } catch (SQLException ex) {
                Logger.getLogger(POFabricView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int r = FabricPO.getSelectedRow();
        String data;
        data = FabricPO.getValueAt(r, 4).toString();
        new NewPOFabric(true, data).setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText("SEARCH.......");
        updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void FabricPOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FabricPOMouseClicked
        jButton9.setVisible(true);
        jButton8.setVisible(true);
    }//GEN-LAST:event_FabricPOMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pg = 1;
        jTextField2.setText(Integer.toString(pg));
        if (pg == 0) {
            offset = (pg) * lim;
        } else {
            offset = (pg - 1) * lim;
        }

        updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (pg > 1) {
            pg--;
            jTextField2.setText(Integer.toString(pg));
        }
        if (pg == 0) {
            offset = (pg) * lim;
        } else {
            offset = (pg - 1) * lim;
        }

        updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        int p = Integer.parseInt((String) jTextField2.getText());
        if (p > maxPages || p < 1) {
        } else {

            pg = p;
            if (pg == 0) {
                offset = (pg) * lim;
            } else {
                offset = (pg - 1) * lim;
            }

            updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
            addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");

        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (pg < maxPages) {
            pg++;
            jTextField2.setText(Integer.toString(pg));
        }
        if (pg == 0) {
            offset = (pg) * lim;
        } else {
            offset = (pg - 1) * lim;
        }
        updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        pg = maxPages;
        jTextField2.setText(Integer.toString(pg));
        if (pg == 0) {
            offset = (pg) * lim;
        } else {
            offset = (pg - 1) * lim;
        }

        updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
        addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().equals("")) {
            lim = 15;
            jComboBox1.setSelectedItem("15");
            pg = 1;
            jTextField2.setText(Integer.toString(pg));
            if (pg == 0) {
                offset = (pg) * lim;
            } else {
                offset = (pg - 1) * lim;
            }
            updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
            addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");
        } else {
            lim = Integer.parseInt((String) jComboBox1.getSelectedItem());
            pg = 1;
            jTextField2.setText(Integer.toString(pg));
            if (pg == 0) {
                offset = (pg) * lim;
            } else {
                offset = (pg - 1) * lim;
            }
            updateMax("SELECT COUNT(*) AS count FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0", jLabel7, jTextField2);
            addToTable("SELECT * FROM splfabric s,pofabric p WHERE s.batchNo=p.batchNo AND PP_Status=0 LIMIT " + lim + " OFFSET " + offset + "");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        
    }//GEN-LAST:event_jTextField1CaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FabricPO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
