/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mainternance;

/**
 *
 * @author pandu
 */
import inventory.dbCon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date; 



public class AddRepair extends javax.swing.JFrame {

    /**
     * Creates new form AddRepair
     */
     dbCon db = new dbCon();
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int row = -1;
     boolean flagForEdit =false;
   validation v=new validation();
   
    public AddRepair() throws  SQLException{
        initComponents();
        
      
        con= db.ConnectDB();
         viewEdit(false);
        
         ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT machinename FROM machine");
        while(rs.next()){
            machname.addItem(rs.getString("machinename"));
        }
        machname.setSelectedIndex(-1);
        
         ResultSet rs1 = con.createStatement().executeQuery("SELECT DISTINCT machinerefno FROM machine");
        while(rs1.next()){
            machrefno.addItem(rs1.getString("machinerefno"));
        }
        machrefno.setSelectedIndex(-1);
        
        clear();
    }

    AddRepair(String machrefno_edit, String machname_edit, String equiname_edit, String freq_edit, String Date_edit, String dept_edit, String status_edit) throws SQLException{
        initComponents();//load init components

        con = db.ConnectDB();//db connection
        ResultSet rs2 = con.createStatement().executeQuery("SELECT DISTINCT machinename FROM machine");
        while(rs2.next()){
            machname.addItem(rs2.getString("machinename"));
        }
        machname.setSelectedIndex(-1);
        
         ResultSet rs3 = con.createStatement().executeQuery("SELECT DISTINCT machinerefno FROM machine");
        while(rs3.next()){
            machrefno.addItem(rs3.getString("machinerefno"));
        }
        machrefno.setSelectedIndex(-1);

        try {
            //set data to swing components
            java.util.Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date = sdf.parse(Date_edit);
            machrefno.setSelectedItem(machrefno_edit);
            machname.setSelectedItem(machname_edit);
            equiname.setText(equiname_edit);
            freq.setSelectedItem(freq_edit);
            Date.setDate(date);
            dept.setSelectedItem(dept_edit);
            statr.setSelectedItem(status_edit);
            flagForEdit=true;
            machrefno.setEditable(false);
            machname.setEditable(false);
           // dept.setEditable(false);
            Date.setEditable(false);
                     
            if(flagForEdit){
                //use to show an edit button instead of add Machine button
                 viewEdit(flagForEdit);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        statr = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        dept = new javax.swing.JComboBox<>();
        Date = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        equiname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        freq = new javax.swing.JComboBox<>();
        machname = new javax.swing.JComboBox<>();
        machrefno = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(514, 482));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, 13));

        jLabel3.setText("Machine Ref no");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 100, 35));

        statr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "not available", "Available" }));
        statr.setSelectedIndex(-1);
        jPanel1.add(statr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 180, 25));

        jLabel6.setText("Department");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 90, 35));

        jLabel7.setText("Repair Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 90, 35));

        submit.setBackground(new java.awt.Color(0, 0, 255));
        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Add Repair Details");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 180, 40));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 490, 13));

        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B/W Qc", "Washing ", "Hydro ", "Wet Qc", "Drying ", "Cool drying", "Chemicals", "A/W Qc" }));
        dept.setSelectedIndex(-1);
        jPanel1.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 180, 25));
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 180, 25));

        jLabel2.setText("Date put into repair");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 110, -1));

        jLabel5.setText("Machine Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Repair Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 30));

        jLabel8.setText("Equipment Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        jPanel1.add(equiname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 180, 25));

        jLabel9.setText("Frequency of Repair");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Minimize.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel14.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel14.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 0, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Close.png"))); // NOI18N
        jLabel17.setText("jLabel14");
        jLabel17.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel17.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 0, -1, -1));

        freq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "daily", "rarely", "oftenly", "occasionaly" }));
        freq.setSelectedIndex(-1);
        jPanel1.add(freq, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 180, 25));

        jPanel1.add(machname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, 30));

        machrefno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        machrefno.setSelectedIndex(-1);
        machrefno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machrefnoActionPerformed(evt);
            }
        });
        jPanel1.add(machrefno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 30));

        btnEdit.setBackground(new java.awt.Color(0, 0, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit  Repair Details");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 180, 40));
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

      boolean formValidate() throws SQLException{
        boolean flag=true;
    if ((machname.getSelectedIndex()) != -1) {   
    if ((statr.getSelectedIndex()) != -1) {
        if((freq.getSelectedIndex())!= -1){
            if((dept.getSelectedIndex())!= -1){
                if((machrefno.getSelectedIndex())!= -1){
                    if(equiname.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Add Equipment name", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                    }
                    else{
                     if(Date.getDate()== null){
                    JOptionPane.showMessageDialog(null, "Add Date", "Error", JOptionPane.ERROR_MESSAGE);
                    flag= false;
                    }
                    }
                    /* if(v.validateDateForward(new SimpleDateFormat("dd-MM-yyyy").format(Date.getDate()), error)){
                    
                      return false;
                    }*/
                }
                else{
                    JOptionPane.showMessageDialog(null, "Add Machine Reference No", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "select department", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Add Frequency", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    else{
        JOptionPane.showMessageDialog(null, "select status", "Error", JOptionPane.ERROR_MESSAGE);
           return false;
    }
    }
     else{
        JOptionPane.showMessageDialog(null, "select machine name", "Error", JOptionPane.ERROR_MESSAGE);
           return false;
    }
        return flag; 
    }
    
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
       try{    
        if((formValidate())==true){
           
        try {

            String machinerefno = String.valueOf(machrefno.getSelectedItem());
            String machinename = String.valueOf(machname.getSelectedItem());
            String equipmentname= equiname.getText();
            String frequency=String.valueOf(freq.getSelectedItem()); 
            Date oDate = Date.getDate();//date selection combo eke name eka.     
            java.sql.Date sqlDate=new java.sql.Date(oDate.getTime());//sql date ekakata convert karala thiyenne
            String department =String.valueOf(dept.getSelectedItem());
            String status=String.valueOf(statr.getSelectedItem());

            String sql = "insert into repair (machinerefno, machinename, equipmentname, frequency,dateofrepair,department,status) values(?,?,?,?,?,?,?)";
                pst = con.prepareStatement(sql);
                pst.setString(1, machinerefno);
                pst.setString(2, machinename);
                pst.setString(3, equipmentname);
                pst.setString(4, frequency);
                pst.setDate(5, sqlDate);//pass a sql date object
                pst.setString(6, department);
                pst.setString(7, status);//status ekata ena walue eka pass karanna.
                
                
                int result = pst.executeUpdate();
                System.out.println(result);
                if (result == 1) {
                     JOptionPane.showMessageDialog (this, "New Repair Added", "Done", JOptionPane.INFORMATION_MESSAGE);
                     clear();
                }
                   
                    } catch (Exception ex) {
                        Logger.getLogger(AddRepair.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
         catch (SQLException ex) {
            Logger.getLogger(AddRepair.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void machrefnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machrefnoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            machname.removeAllItems();
            ResultSet rs2 = con.createStatement().executeQuery("SELECT machinename FROM machine WHERE machinerefno ='"+machrefno.getSelectedItem()+"'");
            while(rs2.next()){
                machname.addItem(rs2.getString("machinename"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddRepair.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        machname.setSelectedIndex(-1);
    }//GEN-LAST:event_machrefnoActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
          try{    
        if((formValidate())==true){
           
        try {

            String machinerefno = String.valueOf(machrefno.getSelectedItem());
            String machinename = String.valueOf(machname.getSelectedItem());
            String equipmentname= equiname.getText();
            String frequency=String.valueOf(freq.getSelectedItem()); 
            Date oDate = Date.getDate();//date selection combo eke name eka.     
            java.sql.Date sqlDate=new java.sql.Date(oDate.getTime());//sql date ekakata convert karala thiyenne
            String department =String.valueOf(dept.getSelectedItem());
            String status=String.valueOf(statr.getSelectedItem());

            String sql = "update repair set  machinename=?, equipmentname=?, frequency=? ,department=? ,status=? where machinerefno=? and dateofrepair=?";
                pst = con.prepareStatement(sql);
                
                pst.setString(1, machinename);
                pst.setString(2, equipmentname);
                pst.setString(3, frequency);
                pst.setString(4, department);
                pst.setString(5, status);//status ekata ena walue eka pass karanna.
                pst.setString(6, machinerefno);
                pst.setDate(7, sqlDate);//pass a sql date object
                
                
                int result = pst.executeUpdate();
                System.out.println(result);
                if (result == 1) {
                     JOptionPane.showMessageDialog (this, " Repair updated", "Done", JOptionPane.INFORMATION_MESSAGE);
                     clear();
                }
                   
                    } catch (Exception ex) {
                        Logger.getLogger(AddRepair.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
         catch (SQLException ex) {
            Logger.getLogger(AddRepair.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddRepair().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddRepair.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker Date;
    public javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JTextField equiname;
    private javax.swing.JLabel error;
    private javax.swing.JComboBox<String> freq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> machname;
    private javax.swing.JComboBox<String> machrefno;
    private javax.swing.JComboBox<String> statr;
    public javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

private void clear() {

        machrefno.setSelectedItem(null);
        machname.setSelectedItem(null);
        equiname.setText(null);
        freq.setSelectedItem(null);
        Date.setDate(null);
        dept.setSelectedItem(null);
        statr.setSelectedItem(null);
        
    }

 private void viewEdit(boolean flag) {
        btnEdit.setVisible(flag);
        submit.setVisible(!flag);
    }

}
