/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mainternance;

/**
 *
 * @author pandu
 */
import inventory.dbCon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date; 
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import Mainternance.ViewMachine;
import java.text.SimpleDateFormat;
import javax.swing.JComponent;

public class AddService extends javax.swing.JFrame {

    /**
     * Creates new form AddService
     */
    dbCon db = new dbCon();
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int row = -1;
    boolean flagForEdit =false;
    String edit;
    validation v=new validation();
    
    public AddService() throws SQLException{
        initComponents();
        
        con=db.ConnectDB();
          viewEdit(false);
         ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT machinerefno FROM machine");
        while(rs.next()){
            machrefno.addItem(rs.getString("machinerefno"));
        }
        machrefno.setSelectedIndex(-1);
         
        clear();
    }

    AddService(String serno_edit, String machrefno_edit, String types_edit, String equiname_edit, String Date_edit) throws SQLException{
         initComponents();//load init components

        con = db.ConnectDB();//db connection
        
         ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT machinerefno FROM machine");
        while(rs.next()){
            machrefno.addItem(rs.getString("machinerefno"));
        }
        machrefno.setSelectedIndex(-1);
this.edit="edit";
        try {
            //set data to swing components
            java.util.Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date = sdf.parse(Date_edit);
            serno.setText(serno_edit);
            machrefno.setSelectedItem(machrefno_edit);
            types.setSelectedItem(types_edit);
            equiname.setText(equiname_edit);
            Date.setDate(date);
            serno.setEditable(false);
            machrefno.setEditable(false);
            flagForEdit=true;
            if(flagForEdit){
                //use to show an edit button instead of add Machine button 
                 viewEdit(flagForEdit);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        types = new javax.swing.JComboBox<>();
        Date = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        serno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        equiname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        machrefno = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(514, 482));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, 13));

        jLabel3.setText("Service  No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, 35));

        jLabel6.setText("Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, 35));

        submit.setBackground(new java.awt.Color(0, 0, 255));
        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Add Service Details");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, 40));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 490, 13));

        types.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full", "Vaccum only", "Wash only" }));
        types.setSelectedIndex(-1);
        jPanel1.add(types, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 25));
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 180, 25));

        jLabel2.setText("Date of  Service");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, -1));
        jPanel1.add(serno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 25));

        jLabel5.setText("Machine Ref no");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Service Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 30));

        jLabel8.setText("Equipment Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));
        jPanel1.add(equiname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 180, 25));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Minimize.png"))); // NOI18N
        jLabel16.setText("jLabel14");
        jLabel16.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel16.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel16.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Close.png"))); // NOI18N
        jLabel17.setText("jLabel14");
        jLabel17.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel17.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        jPanel1.add(machrefno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, 30));

        btnEdit.setBackground(new java.awt.Color(0, 0, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Add Service Details");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, 40));
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 294, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     boolean formValidate() throws SQLException{
        
        boolean flag=true;
       
            if((types.getSelectedIndex())!= -1){
                if((machrefno.getSelectedIndex())!= -1){
                    if(serno.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Add service no", "Error", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                     if(! (serno.getText().startsWith("S") && serno.getText().length() >1) ){
                    JOptionPane.showMessageDialog(null, "Invalid Service Number Format.Enter S<Numeric> Only ", "Error", JOptionPane.ERROR_MESSAGE);
                     return false; 
                    }
                    else
                    {
                        
                      ResultSet rs = con.createStatement().executeQuery("SELECT serviceno FROM service WHERE serviceno = '"+serno.getText()+"'");
                        if(rs.next()){
                            
                                
                               if(edit.equals("edit")){
                                return true;
                            }
                            else{
                                
                                JOptionPane.showMessageDialog(null, "Service No  exist", "Error", JOptionPane.ERROR_MESSAGE);
                                return false;
                            }
                            }
                      
                    }
                    if(Date.getDate()== null){
                    JOptionPane.showMessageDialog(null, "Add Date", "Error", JOptionPane.ERROR_MESSAGE);
                    flag= false;
                    }
                     if(equiname.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Add equimentname", "Error", JOptionPane.ERROR_MESSAGE);
                    flag= false;
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Add Machine Reference No", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                    }   
                
            }
            else{
                JOptionPane.showMessageDialog(null, "select type", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
     
        return flag; 
    }
    
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
       try{    
        if((formValidate())==true){
           
        try {

            String machinerefno = String.valueOf(machrefno.getSelectedItem());
            String serviceno = serno.getText();
            String typeofservice = String.valueOf(types.getSelectedItem());  
            Date oDate = Date.getDate();//date selection combo eke name eka.     
            java.sql.Date sqlDate=new java.sql.Date(oDate.getTime());//sql date ekakata convert karala thiyenne
            String equipmentname =equiname.getText();
            

            String sql = "insert into service (serviceno,machinerefno, typeofservice,equipmentname,dateofservice) values(?,?,?,?,?)";
                pst = con.prepareStatement(sql);
                pst.setString(1, serviceno);
                pst.setString(2, machinerefno);
                pst.setString(3, typeofservice);
                pst.setString(4, equipmentname);
                pst.setDate(5, sqlDate);//pass a sql date object
                
                //pst.setString(6, status);//status ekata ena walue eka pass karanna.
                
                
                int result = pst.executeUpdate();
                System.out.println(result);
                if (result == 1) {
                     JOptionPane.showMessageDialog (this, "New Service Added", "Done", JOptionPane.INFORMATION_MESSAGE);
                     clear();
                }
                   
                    } catch (Exception ex) {
                        Logger.getLogger(AddService.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
         catch (SQLException ex) {
            Logger.getLogger(AddService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{    
        if((formValidate())==true){
           
        try {

            String machinerefno = String.valueOf(machrefno.getSelectedItem());
            String serviceno = serno.getText();
            String typeofservice = String.valueOf(types.getSelectedItem());  
            Date oDate = Date.getDate();//date selection combo eke name eka.     
            java.sql.Date sqlDate=new java.sql.Date(oDate.getTime());//sql date ekakata convert karala thiyenne
            String equipmentname =equiname.getText();
            

            String sql = "update service set machinerefno=?, typeofservice=?, equipmentname=?  ,dateofservice=? where serviceno=?";
                pst = con.prepareStatement(sql);
                
                pst.setString(1, machinerefno);
                pst.setString(2, typeofservice);
                pst.setString(3, equipmentname);
                pst.setDate(4, sqlDate);//pass a sql date object
                pst.setString(5, serviceno);
             
                
                
                int result = pst.executeUpdate();
                System.out.println(result);
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Service  updated");
                        flagForEdit = false;
                        viewEdit(flagForEdit);
                        clear();
                }
                   
                    } catch (Exception ex) {
                        Logger.getLogger(AddService.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
         catch (SQLException ex) {
            Logger.getLogger(AddService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddService().setVisible(true);
                }
                 catch (Exception e) {
                 Logger.getLogger(AddService.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker Date;
    public javax.swing.JButton btnEdit;
    private javax.swing.JTextField equiname;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> machrefno;
    private javax.swing.JTextField serno;
    public javax.swing.JButton submit;
    private javax.swing.JComboBox<String> types;
    // End of variables declaration//GEN-END:variables

private void clear() {

        machrefno.setSelectedItem(null);
        serno.setText(null);
        equiname.setText(null);
        types.setSelectedItem(null);
        Date.setDate(null);
      
        
    }

 private void viewEdit(boolean flag) {
        btnEdit.setVisible(flag);
        submit.setVisible(!flag);
    }
}
