/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mainternance;

/**
 *
 * @author pandu
 */


import inventory.dbCon;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;


public class AddTool extends javax.swing.JFrame {

    /**
     * Creates new form AddTool
     */
     dbCon db = new dbCon();
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int row = -1;
    boolean flagForEdit =false;
     String edit;
      validation v=new validation();
     
    public AddTool() {
        initComponents();
        
        con=db.ConnectDB();
           viewEdit(false);
        clear();
    }

    AddTool(String toolref_edit, String toname_edit, String typet_edit, String qua_edit, String Date_edit)throws SQLException{
        initComponents();//load init components

        con = db.ConnectDB();//db connection
            this.edit="edit";
        try {
            //set data to swing components
            java.util.Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date = sdf.parse(Date_edit);
            toolref.setText(toolref_edit);
            toname.setText(toname_edit);
            typet.setSelectedItem(typet_edit);
            qua.setText(qua_edit);
            Date.setDate(date);
            toolref.setEditable(false);
            flagForEdit=true;
            if(flagForEdit){
                //use to show an edit button instead of add Machine button 
                viewEdit(flagForEdit);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        typet = new javax.swing.JComboBox<>();
        Date = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        toolref = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        toname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        qua = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(514, 482));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, 13));

        jLabel3.setText("Tool Ref  No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 80, 35));

        jLabel6.setText("Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 60, 35));

        submit.setBackground(new java.awt.Color(0, 0, 255));
        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Add Tool Details");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 180, 40));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 490, 13));

        typet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abrasives", "Adhesives/ Sealants/ Tape", "Construction Fabrics", "Electrical eqiupment", "Fittings", "Hand equipment", "Hydraulic equipment", "Lubrications / Oils / Grease", "Lighting supplies", "Welding equipment", " ", " ", " " }));
        typet.setSelectedIndex(-1);
        jPanel1.add(typet, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 25));
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 180, 25));

        jLabel2.setText("Date of  Purchase");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 110, -1));
        jPanel1.add(toolref, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 25));

        jLabel5.setText("Tool Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        toname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tonameActionPerformed(evt);
            }
        });
        jPanel1.add(toname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Tool Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 30));

        jLabel8.setText("Quantity");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        qua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaActionPerformed(evt);
            }
        });
        qua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quaKeyTyped(evt);
            }
        });
        jPanel1.add(qua, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, 25));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Minimize.png"))); // NOI18N
        jLabel16.setText("jLabel14");
        jLabel16.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel16.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel16.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 0, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITP/Images/Close.png"))); // NOI18N
        jLabel17.setText("jLabel14");
        jLabel17.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel17.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 0, -1, -1));

        btnEdit.setBackground(new java.awt.Color(0, 0, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Add Tool Details");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 180, 40));
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 304, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

      boolean formValidate() throws SQLException{
        
        boolean flag=true;
       
           // if((qua.getText().equals(""))){
                if((typet.getSelectedIndex())!= -1){
                    if(toolref.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Add tool number", "Error", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                    if(! (toolref.getText().startsWith("t") && toolref.getText().length() >1) ){
                    JOptionPane.showMessageDialog(null, "Invalid Tool Number Format.Enter t<Numeric> Only ", "Error", JOptionPane.ERROR_MESSAGE);
                     return false; 
                    }
                     else
                     {
                          
                       ResultSet rs = con.createStatement().executeQuery("SELECT toolrefno FROM tool WHERE toolrefno = '"+toolref.getText()+"'");
                        if(rs.next()){
                            
                              if(edit.equals("edit")){
                                return true;
                            }
                            else{
                                
                                JOptionPane.showMessageDialog(null, "Tool No  exist", "Error", JOptionPane.ERROR_MESSAGE);
                                return false;
                            }
                            }
                   
                     }
                    if(Date.getDate()== null){
                    JOptionPane.showMessageDialog(null, "Add Date", "Error", JOptionPane.ERROR_MESSAGE);
                    flag= false;
                    }
                    
                    else{
                    if(toname.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Add Tool Name", "Error", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "select type", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
           // }
           // else{
           //     JOptionPane.showMessageDialog(null, "Add quantity ", "Error", JOptionPane.ERROR_MESSAGE);
           //     return false;
           // }
        return flag; 
    }
      
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
       
     try{    
        if((formValidate())==true){    
        
        try {

            String toolrefno = toolref.getText();
            String toolname = toname.getText();
            String typeoftool = String.valueOf(typet.getSelectedItem());  
            Date oDate = Date.getDate();//date selection combo eke name eka.     
            java.sql.Date sqlDate=new java.sql.Date(oDate.getTime());//sql date ekakata convert karala thiyenne
            String quantity = qua.getText();

            String sql = "insert into tool (toolrefno, toolname, typeoftool, quantity,dateofpurchase) values(?,?,?,?,?)";
                pst = con.prepareStatement(sql);
                pst.setString(1, toolrefno);
                pst.setString(2, toolname);
                pst.setString(3, typeoftool);
                pst.setString(4, quantity);
                pst.setDate(5, sqlDate);//pass a sql date object
                
                int result = pst.executeUpdate();
                System.out.println(result);
                if (result == 1) {
                     JOptionPane.showMessageDialog (this, "New Tool Added", "Done", JOptionPane.INFORMATION_MESSAGE);
                     clear();
                }
                   
                    } catch (Exception ex) {
                        Logger.getLogger(AddTool.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
         catch (SQLException ex) {
            Logger.getLogger(AddTool.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void tonameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tonameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tonameActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void quaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quaKeyPressed
        // TODO add your handling code here:
        
       /* int key=evt.getKeyCode();
        if((key>=evt.VK_0  ) || (key>=evt.VK_NUMPAD0 && key>=evt.VK_NUMPAD9 ) || key==KeyEvent.VK_BACK_SPACE)
        {
            qua.setEditable(true);
            qua.setBackground(Color.yellow);
        }
        else
        {
            qua.setEditable(false);
            qua.setBackground(Color.RED);
        }*/
    }//GEN-LAST:event_quaKeyPressed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        // TODO add your handling code here:
        try{    
        if((formValidate())==true){    
        
        try {

            String toolrefno = toolref.getText();
            String toolname = toname.getText();
            String typeoftool = String.valueOf(typet.getSelectedItem());  
            Date oDate = Date.getDate();//date selection combo eke name eka.     
            java.sql.Date sqlDate=new java.sql.Date(oDate.getTime());//sql date ekakata convert karala thiyenne
            String quantity = qua.getText();

            String sql = "update tool set toolname=?, typeoftool=?, quantity=? ,dateofpurchase=?  where toolrefno=?";
                pst = con.prepareStatement(sql);
                
                pst.setString(1, toolname);
                pst.setString(2, typeoftool);
                pst.setString(3, quantity);
                pst.setDate(4, sqlDate);//pass a sql date object
                pst.setString(5, toolrefno);
                int result = pst.executeUpdate();
                //System.out.println(result);
                if (result == 1) {
                        JOptionPane.showMessageDialog(this, "Tool  updated");
                        flagForEdit = false;
                        viewEdit(flagForEdit);
                        clear();
                }
                   
                    } catch (Exception ex) {
                        Logger.getLogger(AddTool.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
         catch (SQLException ex) {
            Logger.getLogger(AddTool.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void quaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_quaActionPerformed

    private void quaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quaKeyTyped
        // TODO add your handling code here:
         char ch=evt.getKeyChar();
       if(!(Character.isDigit(ch) || (ch == KeyEvent.VK_BACK_SPACE) || ch ==KeyEvent.VK_DELETE ))
       {
           getToolkit().beep();
           evt.consume();
       }
        if (qua.getText().length() >= 3 ) // limit to 3 characters
        {
            getToolkit().beep();    
            evt.consume();
        }    
    }//GEN-LAST:event_quaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker Date;
    public javax.swing.JButton btnEdit;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField qua;
    public javax.swing.JButton submit;
    private javax.swing.JTextField toname;
    private javax.swing.JTextField toolref;
    private javax.swing.JComboBox<String> typet;
    // End of variables declaration//GEN-END:variables

private void clear() {

        toolref.setText(null);
        toname.setText(null);
        //equiname.setText(null);
        typet.setSelectedItem(null);
        Date.setDate(null);
        qua.setText(null);
        
        
    }

 private void viewEdit(boolean flag) {
        btnEdit.setVisible(flag);
        submit.setVisible(!flag);
    }

}
