/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import ITP.Home;
import static inventory.dbCon.con;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Tenusha
 */
public class addColor extends javax.swing.JFrame {

    String st = "";
    String pk = "";
    String pk2 = "";
    String editCol = "";

    /**
     * Creates new form addColor
     */
    public addColor() throws SQLException {
        initComponents();

        AutoCompleteDecorator.decorate(customer);
        AutoCompleteDecorator.decorate(style);

        dbCon d = new dbCon();
        d.connect();
        ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT customer FROM style");
        while (rs.next()) {
            customer.addItem(rs.getString("customer"));
        }
        customer.setSelectedIndex(-1);
    }

    public addColor(String s, String p, String p2, String c) throws SQLException {
        initComponents();
        st = s;
        pk = p;
        pk2 = p2;
        editCol = c;
        dbCon d = new dbCon();
        d.connect();

        ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT customer FROM style");
        while (rs.next()) {
            customer.addItem(rs.getString("customer"));
        }
        ResultSet rs2 = con.createStatement().executeQuery("SELECT styleNo FROM style WHERE customer ='" + pk + "'");
        while (rs2.next()) {
            style.addItem(rs2.getString("styleNo"));
        }

        ResultSet edit = con.createStatement().executeQuery("SELECT * FROM color WHERE customer = '" + pk + "' AND style = '" + pk2 + "' AND color ='" + editCol + "'");
        edit.next();
        colNo.setText(edit.getString("color"));
        colName.setText(edit.getString("colorName"));

        colNo.setEditable(false);
        jLabel1.setText("Edit Style Color");
        jButton1.setText("Edit Color");

        customer.setSelectedItem(pk);
        style.setSelectedItem(pk2);

        customer.setEnabled(false);
        style.setEnabled(false);
        colNo.setEditable(false);
    }

    boolean formValidate() throws SQLException {
        if ((customer.getSelectedIndex()) != -1) {
            if ((style.getSelectedIndex()) != -1) {
                if (colNo.getText().equals("")) {
                    colNo.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                    colNol.setText("please add a color code");
                    return false;
                } else {
                    if (colName.getText().equals("")) {
                        colName.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                        colNamel.setText("please add a color name");
                        return false;
                    } else {
                        ResultSet rs = con.createStatement().executeQuery("SELECT color FROM color WHERE customer = '" + customer.getSelectedItem() + "' AND style ='" + style.getSelectedItem() + "' AND color ='" + colNo.getText() + "'");
                        if (rs.next()) {
                            if (st.equals("edit")) {
                                return true;
                            } else {
                                colNo.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                                colNol.setText("customer's style color exist");
                                return false;
                            }
                        } else {
                            return true;
                        }
                    }
                }
            } else {
                style.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                stylel.setText("please select a style");
                return false;
            }
        } else {
            customer.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
            customerl.setText("please select a customer");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        colNo = new javax.swing.JTextField();
        colName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        customer = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        style = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        colNamel = new javax.swing.JLabel();
        customerl = new javax.swing.JLabel();
        stylel = new javax.swing.JLabel();
        colNol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Minimize.png"))); // NOI18N
        minimize.setAlignmentY(0.0F);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Close.png"))); // NOI18N
        close.setAlignmentY(0.0F);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 13));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Style Color");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 372, -1));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 480, 13));
        jPanel1.add(colNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 290, 35));
        jPanel1.add(colName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 290, 35));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Color Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 70, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Color code");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Color");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 130, 40));

        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 290, 35));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Customer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, 35));

        style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleActionPerformed(evt);
            }
        });
        jPanel1.add(style, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 290, 35));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Style No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, 30));

        colNamel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(colNamel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 335, 290, 20));

        customerl.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(customerl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 155, 290, 20));

        stylel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(stylel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 215, 290, 20));

        colNol.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(colNol, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 275, 290, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        customer.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        customerl.setText("");
        style.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        stylel.setText("");
        colNo.setBorder(BorderFactory.createLineBorder(Color.decode("#a0a0a0")));
        colNol.setText("");
        colName.setBorder(BorderFactory.createLineBorder(Color.decode("#a0a0a0")));
        colNamel.setText("");

        String col = colNo.getText();
        String cName = colName.getText();
        String cus = String.valueOf(customer.getSelectedItem());
        String styl = String.valueOf(style.getSelectedItem());

        try {
            if ((formValidate()) == true) {
                if (st.equals("edit")) {
                    con.prepareStatement("UPDATE color set colorName='" + cName + "' WHERE customer ='" + pk + "' AND style = '" + pk2 + "' AND color ='" + editCol + "'").execute();
                    JOptionPane.showMessageDialog(null, "Color Updated", "Done", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                } else {
                    try {
                        con.prepareStatement("INSERT INTO color VALUES('" + cus + "','" + styl + "','" + col + "','" + cName + "')").execute();
                        JOptionPane.showMessageDialog(null, "New Color Added", "Done", JOptionPane.INFORMATION_MESSAGE);
                        colNo.setText(null);
                        colName.setText(null);
                        customer.setSelectedIndex(-1);
                        style.setSelectedIndex(-1);
                    } catch (SQLException ex) {
                        Logger.getLogger(addColor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(addColor.class.getName()).log(Level.SEVERE, null, ex);
        }
        Home.viewColor.refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        try {
            // TODO add your handling code here:
            style.removeAllItems();
            ResultSet rs2 = con.createStatement().executeQuery("SELECT styleNo FROM style WHERE customer ='" + customer.getSelectedItem() + "' AND type IN ('Garments','Fabrics')");
            while (rs2.next()) {
                style.addItem(rs2.getString("styleNo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(addColor.class.getName()).log(Level.SEVERE, null, ex);

        }
        style.setSelectedIndex(-1);
    }//GEN-LAST:event_customerActionPerformed

    private void styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleActionPerformed
        // TODO add your handling code here:
        //updateColor();
    }//GEN-LAST:event_styleActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new addColor().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(addColor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JTextField colName;
    private javax.swing.JLabel colNamel;
    private javax.swing.JTextField colNo;
    private javax.swing.JLabel colNol;
    private javax.swing.JComboBox<String> customer;
    private javax.swing.JLabel customerl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel minimize;
    private javax.swing.JComboBox<String> style;
    private javax.swing.JLabel stylel;
    // End of variables declaration//GEN-END:variables
}
