/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import ITP.Home;
import static inventory.dbCon.con;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Tenusha
 */
public class addGarments extends javax.swing.JFrame {

    /**
     * Creates new form addGarments
     */
    public addGarments() throws SQLException {
        initComponents();

        AutoCompleteDecorator.decorate(style);

        dbCon d = new dbCon();
        d.connect();
        
        fillStyle();
    }

    void fillStyle() throws SQLException {
        style.removeAllItems();
        ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT styleNo FROM style WHERE type ='Garments' AND styleNo not in (SELECT style from garments)");
        while (rs.next()) {
            style.addItem(rs.getString("styleNo"));
        }
        style.setSelectedIndex(-1);
    }

    boolean formValidate() throws SQLException {
        if (style.getSelectedIndex() != -1) {
            if (item.getText().equals("")) {
                item.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                iteml.setText("please add a garment item");
                return false;
            } else {
                ResultSet rs = con.createStatement().executeQuery("SELECT * FROM garments WHERE style ='" + style.getSelectedItem() + "'");
                if (rs.next()) {
                    style.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                    stylel.setText("style already exist");
                    return false;
                } else {
                    return true;
                }
            }
        } else {
            style.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
            stylel.setText("please select a style");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        style = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        item = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        iteml = new javax.swing.JLabel();
        stylel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleActionPerformed(evt);
            }
        });
        jPanel1.add(style, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 35));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 13));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Garment Item");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 372, -1));

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Minimize.png"))); // NOI18N
        minimize.setAlignmentY(0.0F);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Close.png"))); // NOI18N
        close.setAlignmentY(0.0F);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Garment Item");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 30));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 480, 13));
        jPanel1.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, 35));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Style No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 80, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Garment Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 160, 40));

        iteml.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(iteml, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 220, 20));

        stylel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(stylel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 220, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_styleActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            style.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
            stylel.setText("");
            item.setBorder(BorderFactory.createLineBorder(Color.decode("#a0a0a0")));
            iteml.setText("");

            String itm = item.getText();
            String styl = String.valueOf(style.getSelectedItem());

            if ((formValidate())) {
                try {
                    con.prepareStatement("INSERT INTO garments VALUES('" + styl + "','" + itm + "')").execute();
                    JOptionPane.showMessageDialog(null, "New garment item Added", "Done", JOptionPane.INFORMATION_MESSAGE);
                    item.setText(null);
                    fillStyle();
                } catch (SQLException ex) {
                    Logger.getLogger(addSize.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(addSize.class.getName()).log(Level.SEVERE, null, ex);
        }
        Home.vGarments.refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addGarments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addGarments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addGarments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addGarments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new addGarments().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(addGarments.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JTextField item;
    private javax.swing.JLabel iteml;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel minimize;
    private javax.swing.JComboBox<String> style;
    private javax.swing.JLabel stylel;
    // End of variables declaration//GEN-END:variables
}
