/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import ITP.Home;
import static inventory.dbCon.con;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Tenusha
 */
public class addSize extends javax.swing.JFrame {

    /**
     * Creates new form addSize
     */
    public addSize() throws SQLException {
        initComponents();

        AutoCompleteDecorator.decorate(customer);
        AutoCompleteDecorator.decorate(style);

        dbCon d = new dbCon();
        d.connect();
        ResultSet rs = con.createStatement().executeQuery("SELECT DISTINCT customer FROM style");
        while (rs.next()) {
            customer.addItem(rs.getString("customer"));
        }
        customer.setSelectedIndex(-1);
    }

    boolean formValidate() throws SQLException {
        if (customer.getSelectedIndex() != -1) {
            if (style.getSelectedIndex() != -1) {
                if (size.getText().equals("")) {
                    sizel.setText("please add a size");
                    size.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                    return false;
                } else {
                    ResultSet rs = con.createStatement().executeQuery("SELECT size FROM size WHERE customer = '" + customer.getSelectedItem() + "' AND style ='" + style.getSelectedItem() + "' AND size = '" + size.getText() + "'");
                    if (rs.next()) {
                        sizel.setText("customer's style size exist");
                        size.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                        return false;
                    } else {
                        return true;
                    }
                }
            } else {
                stylel.setText("please select a style");
                style.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
                return false;
            }
        } else {
            customerl.setText("please select a customer");
            customer.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
            //JOptionPane.showMessageDialog(null, "select customer", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        style = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        customer = new javax.swing.JComboBox<>();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        size = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sizel = new javax.swing.JLabel();
        customerl = new javax.swing.JLabel();
        stylel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 470));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleActionPerformed(evt);
            }
        });
        jPanel1.add(style, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 300, 35));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 13));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Style Size");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 372, -1));

        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 300, 35));

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Minimize.png"))); // NOI18N
        minimize.setAlignmentY(0.0F);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryImages/Close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Customer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, 35));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Size");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 70, 30));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 480, 13));
        jPanel1.add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 300, 35));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Style No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Size");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 130, 40));

        sizel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(sizel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 300, 20));

        customerl.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(customerl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 300, 20));

        stylel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(stylel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 300, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        try {
            // TODO add your handling code here:
            style.removeAllItems();
            ResultSet rs2 = con.createStatement().executeQuery("SELECT styleNo FROM style WHERE customer ='" + customer.getSelectedItem() + "' AND type IN ('Garments','Gloves')");
            while (rs2.next()) {
                style.addItem(rs2.getString("styleNo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(addColor.class.getName()).log(Level.SEVERE, null, ex);

        }
        style.setSelectedIndex(-1);
    }//GEN-LAST:event_customerActionPerformed

    private void styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleActionPerformed
        // TODO add your handling code here:
        //updateColor();
    }//GEN-LAST:event_styleActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            style.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
            customer.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
            size.setBorder(BorderFactory.createLineBorder(Color.decode("#a0a0a0")));
            stylel.setText("");
            customerl.setText("");
            sizel.setText("");

            String siz = size.getText();
            String cus = String.valueOf(customer.getSelectedItem());
            String styl = String.valueOf(style.getSelectedItem());

            if ((formValidate()) == true) {
                try {
                    con.prepareStatement("INSERT INTO size VALUES('" + cus + "','" + styl + "','" + siz + "')").execute();
                    JOptionPane.showMessageDialog(null, "New Size Added", "Done", JOptionPane.INFORMATION_MESSAGE);
                    size.setText(null);
                    customer.setSelectedIndex(-1);
                    style.setSelectedIndex(-1);
                } catch (SQLException ex) {
                    Logger.getLogger(addSize.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(addSize.class.getName()).log(Level.SEVERE, null, ex);
        }
        Home.vSize.refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new addSize().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(addSize.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JComboBox<String> customer;
    private javax.swing.JLabel customerl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField size;
    private javax.swing.JLabel sizel;
    private javax.swing.JComboBox<String> style;
    private javax.swing.JLabel stylel;
    // End of variables declaration//GEN-END:variables
}
